//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.27 at 06:04:33 PM EST 
//


package gov.niem.core;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import gov.niem.adapters.xs.AnyURI;
import gov.niem.adapters.xs.Boolean;
import gov.niem.codes.ndex.BinaryCategoryCodeType;
import gov.niem.utility.structures.ObjectType;


/**
 * A data type for a digital representation of an object encoded in a binary format.
 * 
 * <p>Java class for BinaryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BinaryType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://release.niem.gov/niem/structures/5.0/}ObjectType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}BinaryCategoryAbstract" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}BinaryHash" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}BinaryAvailableIndicator" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}BinaryCaptureDate" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}BinaryDescriptionText" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}BinaryFormatAbstract" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}BinaryURI" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;anyAttribute processContents='lax' namespace='urn:us:gov:ic:ntk urn:us:gov:ic:ism'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BinaryType", namespace = "http://release.niem.gov/niem/niem-core/5.0/", propOrder = {
    "binaryCategoryAbstract",
    "binaryHash",
    "binaryAvailableIndicator",
    "binaryCaptureDate",
    "binaryDescriptionText",
    "binaryFormatAbstract",
    "binaryURI"
})
@XmlSeeAlso({
    ImageType.class
})
public class BinaryType
    extends ObjectType
{

    @XmlElementRef(name = "BinaryCategoryAbstract", namespace = "http://release.niem.gov/niem/niem-core/5.0/", type = JAXBElement.class, required = false)
    protected List<JAXBElement<?>> binaryCategoryAbstract;
    @XmlElement(name = "BinaryHash", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<BinaryHashType> binaryHash;
    @XmlElement(name = "BinaryAvailableIndicator", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<Boolean> binaryAvailableIndicator;
    @XmlElement(name = "BinaryCaptureDate", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<DateType> binaryCaptureDate;
    @XmlElement(name = "BinaryDescriptionText", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<TextType> binaryDescriptionText;
    @XmlElementRef(name = "BinaryFormatAbstract", namespace = "http://release.niem.gov/niem/niem-core/5.0/", type = JAXBElement.class, required = false)
    protected List<JAXBElement<?>> binaryFormatAbstract;
    @XmlElement(name = "BinaryURI", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<AnyURI> binaryURI;

    /**
     * Gets the value of the binaryCategoryAbstract property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the binaryCategoryAbstract property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBinaryCategoryAbstract().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link BinaryCategoryCodeType }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getBinaryCategoryAbstract() {
        if (binaryCategoryAbstract == null) {
            binaryCategoryAbstract = new ArrayList<JAXBElement<?>>();
        }
        return this.binaryCategoryAbstract;
    }

    /**
     * Gets the value of the binaryHash property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the binaryHash property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBinaryHash().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BinaryHashType }
     * 
     * 
     */
    public List<BinaryHashType> getBinaryHash() {
        if (binaryHash == null) {
            binaryHash = new ArrayList<BinaryHashType>();
        }
        return this.binaryHash;
    }

    /**
     * Gets the value of the binaryAvailableIndicator property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the binaryAvailableIndicator property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBinaryAvailableIndicator().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Boolean }
     * 
     * 
     */
    public List<Boolean> getBinaryAvailableIndicator() {
        if (binaryAvailableIndicator == null) {
            binaryAvailableIndicator = new ArrayList<Boolean>();
        }
        return this.binaryAvailableIndicator;
    }

    /**
     * Gets the value of the binaryCaptureDate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the binaryCaptureDate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBinaryCaptureDate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DateType }
     * 
     * 
     */
    public List<DateType> getBinaryCaptureDate() {
        if (binaryCaptureDate == null) {
            binaryCaptureDate = new ArrayList<DateType>();
        }
        return this.binaryCaptureDate;
    }

    /**
     * Gets the value of the binaryDescriptionText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the binaryDescriptionText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBinaryDescriptionText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextType }
     * 
     * 
     */
    public List<TextType> getBinaryDescriptionText() {
        if (binaryDescriptionText == null) {
            binaryDescriptionText = new ArrayList<TextType>();
        }
        return this.binaryDescriptionText;
    }

    /**
     * Gets the value of the binaryFormatAbstract property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the binaryFormatAbstract property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBinaryFormatAbstract().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link TextType }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getBinaryFormatAbstract() {
        if (binaryFormatAbstract == null) {
            binaryFormatAbstract = new ArrayList<JAXBElement<?>>();
        }
        return this.binaryFormatAbstract;
    }

    /**
     * Gets the value of the binaryURI property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the binaryURI property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBinaryURI().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AnyURI }
     * 
     * 
     */
    public List<AnyURI> getBinaryURI() {
        if (binaryURI == null) {
            binaryURI = new ArrayList<AnyURI>();
        }
        return this.binaryURI;
    }

}
