//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.28 at 09:56:02 PM EST 
//


package gov.niem.core;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import gov.niem.adapters.xs.Boolean;
import gov.niem.adapters.xs.GYear;
import gov.niem.adapters.xs.String;
import gov.niem.utility.structures.ObjectType;


/**
 * A data type for an article or thing.
 * 
 * <p>Java class for ItemType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ItemType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://release.niem.gov/niem/structures/5.0/}ObjectType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}ItemActionText" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}ItemAgeMeasure" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}ItemBarCodeIdentification" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}ItemBinary" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}ItemBrandName" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}ItemCategoryAbstract" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}ItemColorDescriptionText" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}ItemColorPrimaryAbstract" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}ItemColorSecondaryAbstract" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}ItemConditionAbstract" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}ItemCurrentResaleValue" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}ItemDealerIdentification" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}ItemDescriptionText" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}ItemDisposition" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}ItemFirstSoldYearDate" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}ItemHeightMeasure" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}ItemImage" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}ItemLeaseIndicator" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}ItemLengthMeasure" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}ItemMakeAbstract" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}ItemModelName" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}ItemModelYearDate" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}ItemName" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}ItemOtherIdentification" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}ItemOwner" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}ItemOwnerAppliedID" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}ItemOwnerPurchasedValue" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}ItemOwnershipCategoryAbstract" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}ItemPossessionDescriptionText" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}ItemPossessor" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}ItemQuantity" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}ItemReceiptIdentification" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}ItemRentalIndicator" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}ItemRFIdentification" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}ItemSalesTaxPercent" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}ItemSerialIdentification" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}ItemSizeDescriptionText" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}ItemStateIdentification" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}ItemStatus" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}ItemStyleAbstract" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}ItemUsageText" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}ItemValue" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}ItemVisibleID" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}ItemWeightMeasure" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}ItemWidthMeasure" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}ItemAugmentationPoint" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;anyAttribute processContents='lax' namespace='urn:us:gov:ic:ntk urn:us:gov:ic:ism'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ItemType", namespace = "http://release.niem.gov/niem/niem-core/5.0/", propOrder = {
    "itemActionText",
    "itemAgeMeasure",
    "itemBarCodeIdentification",
    "itemBinary",
    "itemBrandName",
    "itemCategoryAbstract",
    "itemColorDescriptionText",
    "itemColorPrimaryAbstract",
    "itemColorSecondaryAbstract",
    "itemConditionAbstract",
    "itemCurrentResaleValue",
    "itemDealerIdentification",
    "itemDescriptionText",
    "itemDisposition",
    "itemFirstSoldYearDate",
    "itemHeightMeasure",
    "itemImage",
    "itemLeaseIndicator",
    "itemLengthMeasure",
    "itemMakeAbstract",
    "itemModelName",
    "itemModelYearDate",
    "itemName",
    "itemOtherIdentification",
    "itemOwner",
    "itemOwnerAppliedID",
    "itemOwnerPurchasedValue",
    "itemOwnershipCategoryAbstract",
    "itemPossessionDescriptionText",
    "itemPossessor",
    "itemQuantity",
    "itemReceiptIdentification",
    "itemRentalIndicator",
    "itemRFIdentification",
    "itemSalesTaxPercent",
    "itemSerialIdentification",
    "itemSizeDescriptionText",
    "itemStateIdentification",
    "itemStatus",
    "itemStyleAbstract",
    "itemUsageText",
    "itemValue",
    "itemVisibleID",
    "itemWeightMeasure",
    "itemWidthMeasure",
    "itemAugmentationPoint"
})
@XmlSeeAlso({
    SoftwareType.class
})
public class ItemType
    extends ObjectType
{

    @XmlElement(name = "ItemActionText", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<TextType> itemActionText;
    @XmlElement(name = "ItemAgeMeasure", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<TimeMeasureType> itemAgeMeasure;
    @XmlElement(name = "ItemBarCodeIdentification", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<IdentificationType> itemBarCodeIdentification;
    @XmlElement(name = "ItemBinary", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<BinaryType> itemBinary;
    @XmlElement(name = "ItemBrandName", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<ProperNameTextType> itemBrandName;
    @XmlElement(name = "ItemCategoryAbstract", namespace = "http://release.niem.gov/niem/niem-core/5.0/")
    protected List<Object> itemCategoryAbstract;
    @XmlElement(name = "ItemColorDescriptionText", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<TextType> itemColorDescriptionText;
    @XmlElement(name = "ItemColorPrimaryAbstract", namespace = "http://release.niem.gov/niem/niem-core/5.0/")
    protected List<Object> itemColorPrimaryAbstract;
    @XmlElement(name = "ItemColorSecondaryAbstract", namespace = "http://release.niem.gov/niem/niem-core/5.0/")
    protected List<Object> itemColorSecondaryAbstract;
    @XmlElement(name = "ItemConditionAbstract", namespace = "http://release.niem.gov/niem/niem-core/5.0/")
    protected List<Object> itemConditionAbstract;
    @XmlElement(name = "ItemCurrentResaleValue", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<ItemValueType> itemCurrentResaleValue;
    @XmlElement(name = "ItemDealerIdentification", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<IdentificationType> itemDealerIdentification;
    @XmlElement(name = "ItemDescriptionText", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<TextType> itemDescriptionText;
    @XmlElement(name = "ItemDisposition", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<ItemDispositionType> itemDisposition;
    @XmlElement(name = "ItemFirstSoldYearDate", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<GYear> itemFirstSoldYearDate;
    @XmlElement(name = "ItemHeightMeasure", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<LengthMeasureType> itemHeightMeasure;
    @XmlElement(name = "ItemImage", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<ImageType> itemImage;
    @XmlElement(name = "ItemLeaseIndicator", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<Boolean> itemLeaseIndicator;
    @XmlElement(name = "ItemLengthMeasure", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<LengthMeasureType> itemLengthMeasure;
    @XmlElement(name = "ItemMakeAbstract", namespace = "http://release.niem.gov/niem/niem-core/5.0/")
    protected List<Object> itemMakeAbstract;
    @XmlElement(name = "ItemModelName", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<ProperNameTextType> itemModelName;
    @XmlElement(name = "ItemModelYearDate", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<GYear> itemModelYearDate;
    @XmlElement(name = "ItemName", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<TextType> itemName;
    @XmlElement(name = "ItemOtherIdentification", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<IdentificationType> itemOtherIdentification;
    @XmlElement(name = "ItemOwner", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<EntityType> itemOwner;
    @XmlElement(name = "ItemOwnerAppliedID", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<String> itemOwnerAppliedID;
    @XmlElement(name = "ItemOwnerPurchasedValue", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<ItemValueType> itemOwnerPurchasedValue;
    @XmlElement(name = "ItemOwnershipCategoryAbstract", namespace = "http://release.niem.gov/niem/niem-core/5.0/")
    protected List<Object> itemOwnershipCategoryAbstract;
    @XmlElement(name = "ItemPossessionDescriptionText", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<TextType> itemPossessionDescriptionText;
    @XmlElement(name = "ItemPossessor", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<EntityType> itemPossessor;
    @XmlElement(name = "ItemQuantity", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<QuantityType> itemQuantity;
    @XmlElement(name = "ItemReceiptIdentification", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<IdentificationType> itemReceiptIdentification;
    @XmlElement(name = "ItemRentalIndicator", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<Boolean> itemRentalIndicator;
    @XmlElement(name = "ItemRFIdentification", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<IdentificationType> itemRFIdentification;
    @XmlElement(name = "ItemSalesTaxPercent", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<PercentType> itemSalesTaxPercent;
    @XmlElement(name = "ItemSerialIdentification", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<IdentificationType> itemSerialIdentification;
    @XmlElement(name = "ItemSizeDescriptionText", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<TextType> itemSizeDescriptionText;
    @XmlElement(name = "ItemStateIdentification", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<IdentificationType> itemStateIdentification;
    @XmlElement(name = "ItemStatus", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<StatusType> itemStatus;
    @XmlElement(name = "ItemStyleAbstract", namespace = "http://release.niem.gov/niem/niem-core/5.0/")
    protected List<Object> itemStyleAbstract;
    @XmlElement(name = "ItemUsageText", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<TextType> itemUsageText;
    @XmlElement(name = "ItemValue", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<ItemValueType> itemValue;
    @XmlElement(name = "ItemVisibleID", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<String> itemVisibleID;
    @XmlElement(name = "ItemWeightMeasure", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<WeightMeasureType> itemWeightMeasure;
    @XmlElement(name = "ItemWidthMeasure", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<LengthMeasureType> itemWidthMeasure;
    @XmlElement(name = "ItemAugmentationPoint", namespace = "http://release.niem.gov/niem/niem-core/5.0/")
    protected List<Object> itemAugmentationPoint;

    /**
     * Gets the value of the itemActionText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemActionText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemActionText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextType }
     * 
     * 
     */
    public List<TextType> getItemActionText() {
        if (itemActionText == null) {
            itemActionText = new ArrayList<TextType>();
        }
        return this.itemActionText;
    }

    /**
     * Gets the value of the itemAgeMeasure property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemAgeMeasure property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemAgeMeasure().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TimeMeasureType }
     * 
     * 
     */
    public List<TimeMeasureType> getItemAgeMeasure() {
        if (itemAgeMeasure == null) {
            itemAgeMeasure = new ArrayList<TimeMeasureType>();
        }
        return this.itemAgeMeasure;
    }

    /**
     * Gets the value of the itemBarCodeIdentification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemBarCodeIdentification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemBarCodeIdentification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IdentificationType }
     * 
     * 
     */
    public List<IdentificationType> getItemBarCodeIdentification() {
        if (itemBarCodeIdentification == null) {
            itemBarCodeIdentification = new ArrayList<IdentificationType>();
        }
        return this.itemBarCodeIdentification;
    }

    /**
     * Gets the value of the itemBinary property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemBinary property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemBinary().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BinaryType }
     * 
     * 
     */
    public List<BinaryType> getItemBinary() {
        if (itemBinary == null) {
            itemBinary = new ArrayList<BinaryType>();
        }
        return this.itemBinary;
    }

    /**
     * Gets the value of the itemBrandName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemBrandName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemBrandName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProperNameTextType }
     * 
     * 
     */
    public List<ProperNameTextType> getItemBrandName() {
        if (itemBrandName == null) {
            itemBrandName = new ArrayList<ProperNameTextType>();
        }
        return this.itemBrandName;
    }

    /**
     * Gets the value of the itemCategoryAbstract property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemCategoryAbstract property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemCategoryAbstract().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getItemCategoryAbstract() {
        if (itemCategoryAbstract == null) {
            itemCategoryAbstract = new ArrayList<Object>();
        }
        return this.itemCategoryAbstract;
    }

    /**
     * Gets the value of the itemColorDescriptionText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemColorDescriptionText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemColorDescriptionText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextType }
     * 
     * 
     */
    public List<TextType> getItemColorDescriptionText() {
        if (itemColorDescriptionText == null) {
            itemColorDescriptionText = new ArrayList<TextType>();
        }
        return this.itemColorDescriptionText;
    }

    /**
     * Gets the value of the itemColorPrimaryAbstract property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemColorPrimaryAbstract property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemColorPrimaryAbstract().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getItemColorPrimaryAbstract() {
        if (itemColorPrimaryAbstract == null) {
            itemColorPrimaryAbstract = new ArrayList<Object>();
        }
        return this.itemColorPrimaryAbstract;
    }

    /**
     * Gets the value of the itemColorSecondaryAbstract property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemColorSecondaryAbstract property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemColorSecondaryAbstract().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getItemColorSecondaryAbstract() {
        if (itemColorSecondaryAbstract == null) {
            itemColorSecondaryAbstract = new ArrayList<Object>();
        }
        return this.itemColorSecondaryAbstract;
    }

    /**
     * Gets the value of the itemConditionAbstract property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemConditionAbstract property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemConditionAbstract().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getItemConditionAbstract() {
        if (itemConditionAbstract == null) {
            itemConditionAbstract = new ArrayList<Object>();
        }
        return this.itemConditionAbstract;
    }

    /**
     * Gets the value of the itemCurrentResaleValue property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemCurrentResaleValue property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemCurrentResaleValue().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ItemValueType }
     * 
     * 
     */
    public List<ItemValueType> getItemCurrentResaleValue() {
        if (itemCurrentResaleValue == null) {
            itemCurrentResaleValue = new ArrayList<ItemValueType>();
        }
        return this.itemCurrentResaleValue;
    }

    /**
     * Gets the value of the itemDealerIdentification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemDealerIdentification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemDealerIdentification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IdentificationType }
     * 
     * 
     */
    public List<IdentificationType> getItemDealerIdentification() {
        if (itemDealerIdentification == null) {
            itemDealerIdentification = new ArrayList<IdentificationType>();
        }
        return this.itemDealerIdentification;
    }

    /**
     * Gets the value of the itemDescriptionText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemDescriptionText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemDescriptionText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextType }
     * 
     * 
     */
    public List<TextType> getItemDescriptionText() {
        if (itemDescriptionText == null) {
            itemDescriptionText = new ArrayList<TextType>();
        }
        return this.itemDescriptionText;
    }

    /**
     * Gets the value of the itemDisposition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemDisposition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemDisposition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ItemDispositionType }
     * 
     * 
     */
    public List<ItemDispositionType> getItemDisposition() {
        if (itemDisposition == null) {
            itemDisposition = new ArrayList<ItemDispositionType>();
        }
        return this.itemDisposition;
    }

    /**
     * Gets the value of the itemFirstSoldYearDate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemFirstSoldYearDate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemFirstSoldYearDate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GYear }
     * 
     * 
     */
    public List<GYear> getItemFirstSoldYearDate() {
        if (itemFirstSoldYearDate == null) {
            itemFirstSoldYearDate = new ArrayList<GYear>();
        }
        return this.itemFirstSoldYearDate;
    }

    /**
     * Gets the value of the itemHeightMeasure property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemHeightMeasure property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemHeightMeasure().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LengthMeasureType }
     * 
     * 
     */
    public List<LengthMeasureType> getItemHeightMeasure() {
        if (itemHeightMeasure == null) {
            itemHeightMeasure = new ArrayList<LengthMeasureType>();
        }
        return this.itemHeightMeasure;
    }

    /**
     * Gets the value of the itemImage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemImage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemImage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ImageType }
     * 
     * 
     */
    public List<ImageType> getItemImage() {
        if (itemImage == null) {
            itemImage = new ArrayList<ImageType>();
        }
        return this.itemImage;
    }

    /**
     * Gets the value of the itemLeaseIndicator property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemLeaseIndicator property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemLeaseIndicator().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Boolean }
     * 
     * 
     */
    public List<Boolean> getItemLeaseIndicator() {
        if (itemLeaseIndicator == null) {
            itemLeaseIndicator = new ArrayList<Boolean>();
        }
        return this.itemLeaseIndicator;
    }

    /**
     * Gets the value of the itemLengthMeasure property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemLengthMeasure property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemLengthMeasure().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LengthMeasureType }
     * 
     * 
     */
    public List<LengthMeasureType> getItemLengthMeasure() {
        if (itemLengthMeasure == null) {
            itemLengthMeasure = new ArrayList<LengthMeasureType>();
        }
        return this.itemLengthMeasure;
    }

    /**
     * Gets the value of the itemMakeAbstract property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemMakeAbstract property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemMakeAbstract().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getItemMakeAbstract() {
        if (itemMakeAbstract == null) {
            itemMakeAbstract = new ArrayList<Object>();
        }
        return this.itemMakeAbstract;
    }

    /**
     * Gets the value of the itemModelName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemModelName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemModelName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProperNameTextType }
     * 
     * 
     */
    public List<ProperNameTextType> getItemModelName() {
        if (itemModelName == null) {
            itemModelName = new ArrayList<ProperNameTextType>();
        }
        return this.itemModelName;
    }

    /**
     * Gets the value of the itemModelYearDate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemModelYearDate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemModelYearDate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GYear }
     * 
     * 
     */
    public List<GYear> getItemModelYearDate() {
        if (itemModelYearDate == null) {
            itemModelYearDate = new ArrayList<GYear>();
        }
        return this.itemModelYearDate;
    }

    /**
     * Gets the value of the itemName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextType }
     * 
     * 
     */
    public List<TextType> getItemName() {
        if (itemName == null) {
            itemName = new ArrayList<TextType>();
        }
        return this.itemName;
    }

    /**
     * Gets the value of the itemOtherIdentification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemOtherIdentification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemOtherIdentification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IdentificationType }
     * 
     * 
     */
    public List<IdentificationType> getItemOtherIdentification() {
        if (itemOtherIdentification == null) {
            itemOtherIdentification = new ArrayList<IdentificationType>();
        }
        return this.itemOtherIdentification;
    }

    /**
     * Gets the value of the itemOwner property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemOwner property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemOwner().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EntityType }
     * 
     * 
     */
    public List<EntityType> getItemOwner() {
        if (itemOwner == null) {
            itemOwner = new ArrayList<EntityType>();
        }
        return this.itemOwner;
    }

    /**
     * Gets the value of the itemOwnerAppliedID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemOwnerAppliedID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemOwnerAppliedID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getItemOwnerAppliedID() {
        if (itemOwnerAppliedID == null) {
            itemOwnerAppliedID = new ArrayList<String>();
        }
        return this.itemOwnerAppliedID;
    }

    /**
     * Gets the value of the itemOwnerPurchasedValue property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemOwnerPurchasedValue property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemOwnerPurchasedValue().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ItemValueType }
     * 
     * 
     */
    public List<ItemValueType> getItemOwnerPurchasedValue() {
        if (itemOwnerPurchasedValue == null) {
            itemOwnerPurchasedValue = new ArrayList<ItemValueType>();
        }
        return this.itemOwnerPurchasedValue;
    }

    /**
     * Gets the value of the itemOwnershipCategoryAbstract property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemOwnershipCategoryAbstract property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemOwnershipCategoryAbstract().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getItemOwnershipCategoryAbstract() {
        if (itemOwnershipCategoryAbstract == null) {
            itemOwnershipCategoryAbstract = new ArrayList<Object>();
        }
        return this.itemOwnershipCategoryAbstract;
    }

    /**
     * Gets the value of the itemPossessionDescriptionText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemPossessionDescriptionText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemPossessionDescriptionText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextType }
     * 
     * 
     */
    public List<TextType> getItemPossessionDescriptionText() {
        if (itemPossessionDescriptionText == null) {
            itemPossessionDescriptionText = new ArrayList<TextType>();
        }
        return this.itemPossessionDescriptionText;
    }

    /**
     * Gets the value of the itemPossessor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemPossessor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemPossessor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EntityType }
     * 
     * 
     */
    public List<EntityType> getItemPossessor() {
        if (itemPossessor == null) {
            itemPossessor = new ArrayList<EntityType>();
        }
        return this.itemPossessor;
    }

    /**
     * Gets the value of the itemQuantity property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemQuantity property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemQuantity().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QuantityType }
     * 
     * 
     */
    public List<QuantityType> getItemQuantity() {
        if (itemQuantity == null) {
            itemQuantity = new ArrayList<QuantityType>();
        }
        return this.itemQuantity;
    }

    /**
     * Gets the value of the itemReceiptIdentification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemReceiptIdentification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemReceiptIdentification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IdentificationType }
     * 
     * 
     */
    public List<IdentificationType> getItemReceiptIdentification() {
        if (itemReceiptIdentification == null) {
            itemReceiptIdentification = new ArrayList<IdentificationType>();
        }
        return this.itemReceiptIdentification;
    }

    /**
     * Gets the value of the itemRentalIndicator property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemRentalIndicator property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemRentalIndicator().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Boolean }
     * 
     * 
     */
    public List<Boolean> getItemRentalIndicator() {
        if (itemRentalIndicator == null) {
            itemRentalIndicator = new ArrayList<Boolean>();
        }
        return this.itemRentalIndicator;
    }

    /**
     * Gets the value of the itemRFIdentification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemRFIdentification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemRFIdentification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IdentificationType }
     * 
     * 
     */
    public List<IdentificationType> getItemRFIdentification() {
        if (itemRFIdentification == null) {
            itemRFIdentification = new ArrayList<IdentificationType>();
        }
        return this.itemRFIdentification;
    }

    /**
     * Gets the value of the itemSalesTaxPercent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemSalesTaxPercent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemSalesTaxPercent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PercentType }
     * 
     * 
     */
    public List<PercentType> getItemSalesTaxPercent() {
        if (itemSalesTaxPercent == null) {
            itemSalesTaxPercent = new ArrayList<PercentType>();
        }
        return this.itemSalesTaxPercent;
    }

    /**
     * Gets the value of the itemSerialIdentification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemSerialIdentification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemSerialIdentification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IdentificationType }
     * 
     * 
     */
    public List<IdentificationType> getItemSerialIdentification() {
        if (itemSerialIdentification == null) {
            itemSerialIdentification = new ArrayList<IdentificationType>();
        }
        return this.itemSerialIdentification;
    }

    /**
     * Gets the value of the itemSizeDescriptionText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemSizeDescriptionText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemSizeDescriptionText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextType }
     * 
     * 
     */
    public List<TextType> getItemSizeDescriptionText() {
        if (itemSizeDescriptionText == null) {
            itemSizeDescriptionText = new ArrayList<TextType>();
        }
        return this.itemSizeDescriptionText;
    }

    /**
     * Gets the value of the itemStateIdentification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemStateIdentification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemStateIdentification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IdentificationType }
     * 
     * 
     */
    public List<IdentificationType> getItemStateIdentification() {
        if (itemStateIdentification == null) {
            itemStateIdentification = new ArrayList<IdentificationType>();
        }
        return this.itemStateIdentification;
    }

    /**
     * Gets the value of the itemStatus property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemStatus property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemStatus().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StatusType }
     * 
     * 
     */
    public List<StatusType> getItemStatus() {
        if (itemStatus == null) {
            itemStatus = new ArrayList<StatusType>();
        }
        return this.itemStatus;
    }

    /**
     * Gets the value of the itemStyleAbstract property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemStyleAbstract property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemStyleAbstract().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getItemStyleAbstract() {
        if (itemStyleAbstract == null) {
            itemStyleAbstract = new ArrayList<Object>();
        }
        return this.itemStyleAbstract;
    }

    /**
     * Gets the value of the itemUsageText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemUsageText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemUsageText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextType }
     * 
     * 
     */
    public List<TextType> getItemUsageText() {
        if (itemUsageText == null) {
            itemUsageText = new ArrayList<TextType>();
        }
        return this.itemUsageText;
    }

    /**
     * Gets the value of the itemValue property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemValue property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemValue().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ItemValueType }
     * 
     * 
     */
    public List<ItemValueType> getItemValue() {
        if (itemValue == null) {
            itemValue = new ArrayList<ItemValueType>();
        }
        return this.itemValue;
    }

    /**
     * Gets the value of the itemVisibleID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemVisibleID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemVisibleID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getItemVisibleID() {
        if (itemVisibleID == null) {
            itemVisibleID = new ArrayList<String>();
        }
        return this.itemVisibleID;
    }

    /**
     * Gets the value of the itemWeightMeasure property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemWeightMeasure property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemWeightMeasure().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WeightMeasureType }
     * 
     * 
     */
    public List<WeightMeasureType> getItemWeightMeasure() {
        if (itemWeightMeasure == null) {
            itemWeightMeasure = new ArrayList<WeightMeasureType>();
        }
        return this.itemWeightMeasure;
    }

    /**
     * Gets the value of the itemWidthMeasure property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemWidthMeasure property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemWidthMeasure().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LengthMeasureType }
     * 
     * 
     */
    public List<LengthMeasureType> getItemWidthMeasure() {
        if (itemWidthMeasure == null) {
            itemWidthMeasure = new ArrayList<LengthMeasureType>();
        }
        return this.itemWidthMeasure;
    }

    /**
     * Gets the value of the itemAugmentationPoint property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemAugmentationPoint property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemAugmentationPoint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getItemAugmentationPoint() {
        if (itemAugmentationPoint == null) {
            itemAugmentationPoint = new ArrayList<Object>();
        }
        return this.itemAugmentationPoint;
    }

}
