//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.27 at 06:04:33 PM EST 
//


package gov.niem.domains.jxdm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import gov.niem.adapters.xs.Boolean;
import gov.niem.core.ActivityType;
import gov.niem.core.DocumentType;
import gov.niem.core.NumericType;
import gov.niem.core.PersonType;


/**
 * A data type for a live birth of a human being.
 * 
 * <p>Java class for BirthType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BirthType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://release.niem.gov/niem/niem-core/5.0/}ActivityType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/domains/jxdm/7.0/}BirthAttendant" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/domains/jxdm/7.0/}BirthChildBirthOrderNumeric" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/domains/jxdm/7.0/}BirthRegistration" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/domains/jxdm/7.0/}PersonHospitalBirthIndicator" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/domains/jxdm/7.0/}BirthAugmentationPoint" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;anyAttribute processContents='lax' namespace='urn:us:gov:ic:ntk urn:us:gov:ic:ism'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BirthType", namespace = "http://release.niem.gov/niem/domains/jxdm/7.0/", propOrder = {
    "birthAttendant",
    "birthChildBirthOrderNumeric",
    "birthRegistration",
    "personHospitalBirthIndicator",
    "birthAugmentationPoint"
})
public class BirthType
    extends ActivityType
{

    @XmlElement(name = "BirthAttendant", namespace = "http://release.niem.gov/niem/domains/jxdm/7.0/", nillable = true)
    protected List<PersonType> birthAttendant;
    @XmlElement(name = "BirthChildBirthOrderNumeric", namespace = "http://release.niem.gov/niem/domains/jxdm/7.0/", nillable = true)
    protected List<NumericType> birthChildBirthOrderNumeric;
    @XmlElement(name = "BirthRegistration", namespace = "http://release.niem.gov/niem/domains/jxdm/7.0/", nillable = true)
    protected List<DocumentType> birthRegistration;
    @XmlElement(name = "PersonHospitalBirthIndicator", namespace = "http://release.niem.gov/niem/domains/jxdm/7.0/", nillable = true)
    protected List<Boolean> personHospitalBirthIndicator;
    @XmlElement(name = "BirthAugmentationPoint", namespace = "http://release.niem.gov/niem/domains/jxdm/7.0/")
    protected List<Object> birthAugmentationPoint;

    /**
     * Gets the value of the birthAttendant property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the birthAttendant property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBirthAttendant().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PersonType }
     * 
     * 
     */
    public List<PersonType> getBirthAttendant() {
        if (birthAttendant == null) {
            birthAttendant = new ArrayList<PersonType>();
        }
        return this.birthAttendant;
    }

    /**
     * Gets the value of the birthChildBirthOrderNumeric property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the birthChildBirthOrderNumeric property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBirthChildBirthOrderNumeric().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NumericType }
     * 
     * 
     */
    public List<NumericType> getBirthChildBirthOrderNumeric() {
        if (birthChildBirthOrderNumeric == null) {
            birthChildBirthOrderNumeric = new ArrayList<NumericType>();
        }
        return this.birthChildBirthOrderNumeric;
    }

    /**
     * Gets the value of the birthRegistration property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the birthRegistration property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBirthRegistration().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DocumentType }
     * 
     * 
     */
    public List<DocumentType> getBirthRegistration() {
        if (birthRegistration == null) {
            birthRegistration = new ArrayList<DocumentType>();
        }
        return this.birthRegistration;
    }

    /**
     * Gets the value of the personHospitalBirthIndicator property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the personHospitalBirthIndicator property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPersonHospitalBirthIndicator().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Boolean }
     * 
     * 
     */
    public List<Boolean> getPersonHospitalBirthIndicator() {
        if (personHospitalBirthIndicator == null) {
            personHospitalBirthIndicator = new ArrayList<Boolean>();
        }
        return this.personHospitalBirthIndicator;
    }

    /**
     * Gets the value of the birthAugmentationPoint property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the birthAugmentationPoint property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBirthAugmentationPoint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getBirthAugmentationPoint() {
        if (birthAugmentationPoint == null) {
            birthAugmentationPoint = new ArrayList<Object>();
        }
        return this.birthAugmentationPoint;
    }

}
