//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.27 at 06:04:33 PM EST 
//


package gov.niem.domains.jxdm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import gov.niem.adapters.xs.Boolean;
import gov.niem.adapters.xs.NonNegativeInteger;
import gov.niem.codes.aamva_d20.DriverLicenseClassCodeType;
import gov.niem.core.IdentificationType;
import gov.niem.core.TextType;


/**
 * A data type for a license issued to a person granting driving privileges.
 * 
 * <p>Java class for DriverLicenseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DriverLicenseType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://release.niem.gov/niem/domains/jxdm/7.0/}DriverLicenseBaseType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/domains/jxdm/7.0/}DriverLicenseEnhancedIndicator" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/domains/jxdm/7.0/}DriverLicenseCommercialClassAbstract" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/domains/jxdm/7.0/}DriverLicenseCommercialStatusAbstract" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/domains/jxdm/7.0/}DriverLicenseNonCommercialClassText" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/domains/jxdm/7.0/}DriverLicenseNonCommercialStatusAbstract" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/domains/jxdm/7.0/}DriverLicensePermit" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/domains/jxdm/7.0/}DriverLicensePermitQuantity" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/domains/jxdm/7.0/}DriverLicenseWithdrawal" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/domains/jxdm/7.0/}DriverLicenseWithdrawalPendingIndicator" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/domains/jxdm/7.0/}DriverLicenseCardIdentification" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/domains/jxdm/7.0/}DriverLicenseRestriction" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/domains/jxdm/7.0/}DriverLicenseEndorsement" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/domains/jxdm/7.0/}DriverLicenseAugmentationPoint" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;anyAttribute processContents='lax' namespace='urn:us:gov:ic:ntk urn:us:gov:ic:ism'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DriverLicenseType", namespace = "http://release.niem.gov/niem/domains/jxdm/7.0/", propOrder = {
    "driverLicenseEnhancedIndicator",
    "driverLicenseCommercialClassAbstract",
    "driverLicenseCommercialStatusAbstract",
    "driverLicenseNonCommercialClassText",
    "driverLicenseNonCommercialStatusAbstract",
    "driverLicensePermit",
    "driverLicensePermitQuantity",
    "driverLicenseWithdrawal",
    "driverLicenseWithdrawalPendingIndicator",
    "driverLicenseCardIdentification",
    "driverLicenseRestriction",
    "driverLicenseEndorsement",
    "driverLicenseAugmentationPoint"
})
public class DriverLicenseType
    extends DriverLicenseBaseType
{

    @XmlElement(name = "DriverLicenseEnhancedIndicator", namespace = "http://release.niem.gov/niem/domains/jxdm/7.0/", nillable = true)
    protected List<Boolean> driverLicenseEnhancedIndicator;
    @XmlElementRef(name = "DriverLicenseCommercialClassAbstract", namespace = "http://release.niem.gov/niem/domains/jxdm/7.0/", type = JAXBElement.class, required = false)
    protected List<JAXBElement<?>> driverLicenseCommercialClassAbstract;
    @XmlElement(name = "DriverLicenseCommercialStatusAbstract", namespace = "http://release.niem.gov/niem/domains/jxdm/7.0/")
    protected List<Object> driverLicenseCommercialStatusAbstract;
    @XmlElement(name = "DriverLicenseNonCommercialClassText", namespace = "http://release.niem.gov/niem/domains/jxdm/7.0/", nillable = true)
    protected List<TextType> driverLicenseNonCommercialClassText;
    @XmlElement(name = "DriverLicenseNonCommercialStatusAbstract", namespace = "http://release.niem.gov/niem/domains/jxdm/7.0/")
    protected List<Object> driverLicenseNonCommercialStatusAbstract;
    @XmlElement(name = "DriverLicensePermit", namespace = "http://release.niem.gov/niem/domains/jxdm/7.0/", nillable = true)
    protected List<DriverLicensePermitType> driverLicensePermit;
    @XmlElement(name = "DriverLicensePermitQuantity", namespace = "http://release.niem.gov/niem/domains/jxdm/7.0/", nillable = true)
    protected List<NonNegativeInteger> driverLicensePermitQuantity;
    @XmlElement(name = "DriverLicenseWithdrawal", namespace = "http://release.niem.gov/niem/domains/jxdm/7.0/", nillable = true)
    protected List<DriverLicenseWithdrawalType> driverLicenseWithdrawal;
    @XmlElement(name = "DriverLicenseWithdrawalPendingIndicator", namespace = "http://release.niem.gov/niem/domains/jxdm/7.0/", nillable = true)
    protected List<Boolean> driverLicenseWithdrawalPendingIndicator;
    @XmlElement(name = "DriverLicenseCardIdentification", namespace = "http://release.niem.gov/niem/domains/jxdm/7.0/", nillable = true)
    protected List<IdentificationType> driverLicenseCardIdentification;
    @XmlElement(name = "DriverLicenseRestriction", namespace = "http://release.niem.gov/niem/domains/jxdm/7.0/", nillable = true)
    protected List<DriverLicenseRestrictionType> driverLicenseRestriction;
    @XmlElement(name = "DriverLicenseEndorsement", namespace = "http://release.niem.gov/niem/domains/jxdm/7.0/", nillable = true)
    protected List<DriverLicenseEndorsementType> driverLicenseEndorsement;
    @XmlElement(name = "DriverLicenseAugmentationPoint", namespace = "http://release.niem.gov/niem/domains/jxdm/7.0/")
    protected List<Object> driverLicenseAugmentationPoint;

    /**
     * Gets the value of the driverLicenseEnhancedIndicator property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the driverLicenseEnhancedIndicator property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDriverLicenseEnhancedIndicator().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Boolean }
     * 
     * 
     */
    public List<Boolean> getDriverLicenseEnhancedIndicator() {
        if (driverLicenseEnhancedIndicator == null) {
            driverLicenseEnhancedIndicator = new ArrayList<Boolean>();
        }
        return this.driverLicenseEnhancedIndicator;
    }

    /**
     * Gets the value of the driverLicenseCommercialClassAbstract property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the driverLicenseCommercialClassAbstract property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDriverLicenseCommercialClassAbstract().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link DriverLicenseClassCodeType }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getDriverLicenseCommercialClassAbstract() {
        if (driverLicenseCommercialClassAbstract == null) {
            driverLicenseCommercialClassAbstract = new ArrayList<JAXBElement<?>>();
        }
        return this.driverLicenseCommercialClassAbstract;
    }

    /**
     * Gets the value of the driverLicenseCommercialStatusAbstract property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the driverLicenseCommercialStatusAbstract property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDriverLicenseCommercialStatusAbstract().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getDriverLicenseCommercialStatusAbstract() {
        if (driverLicenseCommercialStatusAbstract == null) {
            driverLicenseCommercialStatusAbstract = new ArrayList<Object>();
        }
        return this.driverLicenseCommercialStatusAbstract;
    }

    /**
     * Gets the value of the driverLicenseNonCommercialClassText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the driverLicenseNonCommercialClassText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDriverLicenseNonCommercialClassText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextType }
     * 
     * 
     */
    public List<TextType> getDriverLicenseNonCommercialClassText() {
        if (driverLicenseNonCommercialClassText == null) {
            driverLicenseNonCommercialClassText = new ArrayList<TextType>();
        }
        return this.driverLicenseNonCommercialClassText;
    }

    /**
     * Gets the value of the driverLicenseNonCommercialStatusAbstract property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the driverLicenseNonCommercialStatusAbstract property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDriverLicenseNonCommercialStatusAbstract().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getDriverLicenseNonCommercialStatusAbstract() {
        if (driverLicenseNonCommercialStatusAbstract == null) {
            driverLicenseNonCommercialStatusAbstract = new ArrayList<Object>();
        }
        return this.driverLicenseNonCommercialStatusAbstract;
    }

    /**
     * Gets the value of the driverLicensePermit property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the driverLicensePermit property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDriverLicensePermit().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DriverLicensePermitType }
     * 
     * 
     */
    public List<DriverLicensePermitType> getDriverLicensePermit() {
        if (driverLicensePermit == null) {
            driverLicensePermit = new ArrayList<DriverLicensePermitType>();
        }
        return this.driverLicensePermit;
    }

    /**
     * Gets the value of the driverLicensePermitQuantity property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the driverLicensePermitQuantity property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDriverLicensePermitQuantity().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NonNegativeInteger }
     * 
     * 
     */
    public List<NonNegativeInteger> getDriverLicensePermitQuantity() {
        if (driverLicensePermitQuantity == null) {
            driverLicensePermitQuantity = new ArrayList<NonNegativeInteger>();
        }
        return this.driverLicensePermitQuantity;
    }

    /**
     * Gets the value of the driverLicenseWithdrawal property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the driverLicenseWithdrawal property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDriverLicenseWithdrawal().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DriverLicenseWithdrawalType }
     * 
     * 
     */
    public List<DriverLicenseWithdrawalType> getDriverLicenseWithdrawal() {
        if (driverLicenseWithdrawal == null) {
            driverLicenseWithdrawal = new ArrayList<DriverLicenseWithdrawalType>();
        }
        return this.driverLicenseWithdrawal;
    }

    /**
     * Gets the value of the driverLicenseWithdrawalPendingIndicator property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the driverLicenseWithdrawalPendingIndicator property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDriverLicenseWithdrawalPendingIndicator().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Boolean }
     * 
     * 
     */
    public List<Boolean> getDriverLicenseWithdrawalPendingIndicator() {
        if (driverLicenseWithdrawalPendingIndicator == null) {
            driverLicenseWithdrawalPendingIndicator = new ArrayList<Boolean>();
        }
        return this.driverLicenseWithdrawalPendingIndicator;
    }

    /**
     * Gets the value of the driverLicenseCardIdentification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the driverLicenseCardIdentification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDriverLicenseCardIdentification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IdentificationType }
     * 
     * 
     */
    public List<IdentificationType> getDriverLicenseCardIdentification() {
        if (driverLicenseCardIdentification == null) {
            driverLicenseCardIdentification = new ArrayList<IdentificationType>();
        }
        return this.driverLicenseCardIdentification;
    }

    /**
     * Gets the value of the driverLicenseRestriction property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the driverLicenseRestriction property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDriverLicenseRestriction().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DriverLicenseRestrictionType }
     * 
     * 
     */
    public List<DriverLicenseRestrictionType> getDriverLicenseRestriction() {
        if (driverLicenseRestriction == null) {
            driverLicenseRestriction = new ArrayList<DriverLicenseRestrictionType>();
        }
        return this.driverLicenseRestriction;
    }

    /**
     * Gets the value of the driverLicenseEndorsement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the driverLicenseEndorsement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDriverLicenseEndorsement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DriverLicenseEndorsementType }
     * 
     * 
     */
    public List<DriverLicenseEndorsementType> getDriverLicenseEndorsement() {
        if (driverLicenseEndorsement == null) {
            driverLicenseEndorsement = new ArrayList<DriverLicenseEndorsementType>();
        }
        return this.driverLicenseEndorsement;
    }

    /**
     * Gets the value of the driverLicenseAugmentationPoint property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the driverLicenseAugmentationPoint property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDriverLicenseAugmentationPoint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getDriverLicenseAugmentationPoint() {
        if (driverLicenseAugmentationPoint == null) {
            driverLicenseAugmentationPoint = new ArrayList<Object>();
        }
        return this.driverLicenseAugmentationPoint;
    }

}
