//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.27 at 06:04:33 PM EST 
//


package gov.niem.domains.jxdm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import gov.niem.codes.aamva_d20.DrivingStatusCodeType;
import gov.niem.codes.mmucc.DriverLicensePermitStatusCodeType;
import gov.niem.core.TextType;


/**
 * A data type for a driver license permit issued to a driver granting conditional or limited driving privileges.
 * 
 * <p>Java class for DriverLicensePermitType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DriverLicensePermitType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://release.niem.gov/niem/domains/jxdm/7.0/}DriverLicenseBaseType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/domains/jxdm/7.0/}DriverLicensePermitClassificationText" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/domains/jxdm/7.0/}DriverLicensePermitStatusAbstract" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/domains/jxdm/7.0/}DriverLicensePermitRestriction" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/domains/jxdm/7.0/}DriverLicensePermitEndorsement" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/domains/jxdm/7.0/}DriverLicensePermitAugmentationPoint" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;anyAttribute processContents='lax' namespace='urn:us:gov:ic:ntk urn:us:gov:ic:ism'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DriverLicensePermitType", namespace = "http://release.niem.gov/niem/domains/jxdm/7.0/", propOrder = {
    "driverLicensePermitClassificationText",
    "driverLicensePermitStatusAbstract",
    "driverLicensePermitRestriction",
    "driverLicensePermitEndorsement",
    "driverLicensePermitAugmentationPoint"
})
public class DriverLicensePermitType
    extends DriverLicenseBaseType
{

    @XmlElement(name = "DriverLicensePermitClassificationText", namespace = "http://release.niem.gov/niem/domains/jxdm/7.0/", nillable = true)
    protected List<TextType> driverLicensePermitClassificationText;
    @XmlElementRef(name = "DriverLicensePermitStatusAbstract", namespace = "http://release.niem.gov/niem/domains/jxdm/7.0/", type = JAXBElement.class, required = false)
    protected List<JAXBElement<?>> driverLicensePermitStatusAbstract;
    @XmlElement(name = "DriverLicensePermitRestriction", namespace = "http://release.niem.gov/niem/domains/jxdm/7.0/", nillable = true)
    protected List<DriverLicensePermitRestrictionType> driverLicensePermitRestriction;
    @XmlElement(name = "DriverLicensePermitEndorsement", namespace = "http://release.niem.gov/niem/domains/jxdm/7.0/", nillable = true)
    protected List<DriverLicensePermitEndorsementType> driverLicensePermitEndorsement;
    @XmlElement(name = "DriverLicensePermitAugmentationPoint", namespace = "http://release.niem.gov/niem/domains/jxdm/7.0/")
    protected List<Object> driverLicensePermitAugmentationPoint;

    /**
     * Gets the value of the driverLicensePermitClassificationText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the driverLicensePermitClassificationText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDriverLicensePermitClassificationText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextType }
     * 
     * 
     */
    public List<TextType> getDriverLicensePermitClassificationText() {
        if (driverLicensePermitClassificationText == null) {
            driverLicensePermitClassificationText = new ArrayList<TextType>();
        }
        return this.driverLicensePermitClassificationText;
    }

    /**
     * Gets the value of the driverLicensePermitStatusAbstract property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the driverLicensePermitStatusAbstract property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDriverLicensePermitStatusAbstract().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link DrivingStatusCodeType }{@code >}
     * {@link JAXBElement }{@code <}{@link DriverLicensePermitStatusCodeType }{@code >}
     * {@link JAXBElement }{@code <}{@link TextType }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getDriverLicensePermitStatusAbstract() {
        if (driverLicensePermitStatusAbstract == null) {
            driverLicensePermitStatusAbstract = new ArrayList<JAXBElement<?>>();
        }
        return this.driverLicensePermitStatusAbstract;
    }

    /**
     * Gets the value of the driverLicensePermitRestriction property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the driverLicensePermitRestriction property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDriverLicensePermitRestriction().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DriverLicensePermitRestrictionType }
     * 
     * 
     */
    public List<DriverLicensePermitRestrictionType> getDriverLicensePermitRestriction() {
        if (driverLicensePermitRestriction == null) {
            driverLicensePermitRestriction = new ArrayList<DriverLicensePermitRestrictionType>();
        }
        return this.driverLicensePermitRestriction;
    }

    /**
     * Gets the value of the driverLicensePermitEndorsement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the driverLicensePermitEndorsement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDriverLicensePermitEndorsement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DriverLicensePermitEndorsementType }
     * 
     * 
     */
    public List<DriverLicensePermitEndorsementType> getDriverLicensePermitEndorsement() {
        if (driverLicensePermitEndorsement == null) {
            driverLicensePermitEndorsement = new ArrayList<DriverLicensePermitEndorsementType>();
        }
        return this.driverLicensePermitEndorsement;
    }

    /**
     * Gets the value of the driverLicensePermitAugmentationPoint property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the driverLicensePermitAugmentationPoint property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDriverLicensePermitAugmentationPoint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getDriverLicensePermitAugmentationPoint() {
        if (driverLicensePermitAugmentationPoint == null) {
            driverLicensePermitAugmentationPoint = new ArrayList<Object>();
        }
        return this.driverLicensePermitAugmentationPoint;
    }

}
