//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.02 at 04:56:07 PM EST 
//


package gov.niem.domains.jxdm;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PersonSexCodeSimpleType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PersonSexCodeSimpleType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="F"/&gt;
 *     &lt;enumeration value="M"/&gt;
 *     &lt;enumeration value="U"/&gt;
 *     &lt;enumeration value="X"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "PersonSexCodeSimpleType", namespace = "http://release.niem.gov/niem/domains/jxdm/7.0/")
@XmlEnum
public enum PersonSexCodeSimpleType {


    /**
     * FEMALE
     * 
     */
    F,

    /**
     * MALE
     * 
     */
    M,

    /**
     * UNKNOWN / UNSPECIFIED
     * 
     */
    U,

    /**
     * NON-BINARY
     * 
     */
    X;

    public String value() {
        return name();
    }

    public static PersonSexCodeSimpleType fromValue(String v) {
        return valueOf(v);
    }

}
