//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.27 at 04:09:22 PM EST 
//


package gov.niem.domains.intelligence;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import gov.niem.adapters.xs.Boolean;
import gov.niem.core.IdentificationType;
import gov.niem.core.TextType;
import gov.niem.utility.structures.AugmentationType;


/**
 * A data type for additional information about an identification.
 * 
 * <p>Java class for IdentificationAugmentationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IdentificationAugmentationType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://release.niem.gov/niem/structures/5.0/}AugmentationType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/domains/intelligence/5.0/}AuthenticIndicator" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/domains/intelligence/5.0/}IdentificationIssuingCountryAbstract" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/domains/intelligence/5.0/}IdentificationIssuingStateName" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/domains/intelligence/5.0/}IdentificationIssuingLocalityText" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/domains/intelligence/5.0/}PersonInIdentification" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;anyAttribute processContents='lax' namespace='urn:us:gov:ic:ntk urn:us:gov:ic:ism'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IdentificationAugmentationType", namespace = "http://release.niem.gov/niem/domains/intelligence/5.0/", propOrder = {
    "authenticIndicator",
    "identificationIssuingCountryAbstract",
    "identificationIssuingStateName",
    "identificationIssuingLocalityText",
    "personInIdentification"
})
public class IdentificationAugmentationType
    extends AugmentationType
{

    @XmlElement(name = "AuthenticIndicator", namespace = "http://release.niem.gov/niem/domains/intelligence/5.0/", nillable = true)
    protected List<Boolean> authenticIndicator;
    @XmlElement(name = "IdentificationIssuingCountryAbstract", namespace = "http://release.niem.gov/niem/domains/intelligence/5.0/")
    protected List<Object> identificationIssuingCountryAbstract;
    @XmlElement(name = "IdentificationIssuingStateName", namespace = "http://release.niem.gov/niem/domains/intelligence/5.0/", nillable = true)
    protected List<TextType> identificationIssuingStateName;
    @XmlElement(name = "IdentificationIssuingLocalityText", namespace = "http://release.niem.gov/niem/domains/intelligence/5.0/", nillable = true)
    protected List<TextType> identificationIssuingLocalityText;
    @XmlElement(name = "PersonInIdentification", namespace = "http://release.niem.gov/niem/domains/intelligence/5.0/", nillable = true)
    protected List<IdentificationType> personInIdentification;

    /**
     * Gets the value of the authenticIndicator property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the authenticIndicator property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAuthenticIndicator().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Boolean }
     * 
     * 
     */
    public List<Boolean> getAuthenticIndicator() {
        if (authenticIndicator == null) {
            authenticIndicator = new ArrayList<Boolean>();
        }
        return this.authenticIndicator;
    }

    /**
     * Gets the value of the identificationIssuingCountryAbstract property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the identificationIssuingCountryAbstract property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIdentificationIssuingCountryAbstract().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getIdentificationIssuingCountryAbstract() {
        if (identificationIssuingCountryAbstract == null) {
            identificationIssuingCountryAbstract = new ArrayList<Object>();
        }
        return this.identificationIssuingCountryAbstract;
    }

    /**
     * Gets the value of the identificationIssuingStateName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the identificationIssuingStateName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIdentificationIssuingStateName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextType }
     * 
     * 
     */
    public List<TextType> getIdentificationIssuingStateName() {
        if (identificationIssuingStateName == null) {
            identificationIssuingStateName = new ArrayList<TextType>();
        }
        return this.identificationIssuingStateName;
    }

    /**
     * Gets the value of the identificationIssuingLocalityText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the identificationIssuingLocalityText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIdentificationIssuingLocalityText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextType }
     * 
     * 
     */
    public List<TextType> getIdentificationIssuingLocalityText() {
        if (identificationIssuingLocalityText == null) {
            identificationIssuingLocalityText = new ArrayList<TextType>();
        }
        return this.identificationIssuingLocalityText;
    }

    /**
     * Gets the value of the personInIdentification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the personInIdentification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPersonInIdentification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IdentificationType }
     * 
     * 
     */
    public List<IdentificationType> getPersonInIdentification() {
        if (personInIdentification == null) {
            personInIdentification = new ArrayList<IdentificationType>();
        }
        return this.personInIdentification;
    }

}
