//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.27 at 03:48:01 PM EST 
//


package gov.niem.codes.ncic;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.niem.codes.ncic package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.niem.codes.ncic
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CMCCodeType }
     * 
     */
    public CMCCodeType createCMCCodeType() {
        return new CMCCodeType();
    }

    /**
     * Create an instance of {@link CRCCodeType }
     * 
     */
    public CRCCodeType createCRCCodeType() {
        return new CRCCodeType();
    }

}
