//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.02 at 04:56:07 PM EST 
//


package gov.niem.codes.genc;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CountryAlpha3CodeSimpleType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CountryAlpha3CodeSimpleType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="ABW"/&gt;
 *     &lt;enumeration value="AFG"/&gt;
 *     &lt;enumeration value="AGO"/&gt;
 *     &lt;enumeration value="AIA"/&gt;
 *     &lt;enumeration value="ALB"/&gt;
 *     &lt;enumeration value="AND"/&gt;
 *     &lt;enumeration value="ARE"/&gt;
 *     &lt;enumeration value="ARG"/&gt;
 *     &lt;enumeration value="ARM"/&gt;
 *     &lt;enumeration value="ASM"/&gt;
 *     &lt;enumeration value="ATA"/&gt;
 *     &lt;enumeration value="ATF"/&gt;
 *     &lt;enumeration value="ATG"/&gt;
 *     &lt;enumeration value="AUS"/&gt;
 *     &lt;enumeration value="AUT"/&gt;
 *     &lt;enumeration value="AX1"/&gt;
 *     &lt;enumeration value="AX2"/&gt;
 *     &lt;enumeration value="AX3"/&gt;
 *     &lt;enumeration value="AZE"/&gt;
 *     &lt;enumeration value="BDI"/&gt;
 *     &lt;enumeration value="BEL"/&gt;
 *     &lt;enumeration value="BEN"/&gt;
 *     &lt;enumeration value="BES"/&gt;
 *     &lt;enumeration value="BFA"/&gt;
 *     &lt;enumeration value="BGD"/&gt;
 *     &lt;enumeration value="BGR"/&gt;
 *     &lt;enumeration value="BHR"/&gt;
 *     &lt;enumeration value="BHS"/&gt;
 *     &lt;enumeration value="BIH"/&gt;
 *     &lt;enumeration value="BLM"/&gt;
 *     &lt;enumeration value="BLR"/&gt;
 *     &lt;enumeration value="BLZ"/&gt;
 *     &lt;enumeration value="BMU"/&gt;
 *     &lt;enumeration value="BOL"/&gt;
 *     &lt;enumeration value="BRA"/&gt;
 *     &lt;enumeration value="BRB"/&gt;
 *     &lt;enumeration value="BRN"/&gt;
 *     &lt;enumeration value="BTN"/&gt;
 *     &lt;enumeration value="BVT"/&gt;
 *     &lt;enumeration value="BWA"/&gt;
 *     &lt;enumeration value="CAF"/&gt;
 *     &lt;enumeration value="CAN"/&gt;
 *     &lt;enumeration value="CCK"/&gt;
 *     &lt;enumeration value="CHE"/&gt;
 *     &lt;enumeration value="CHL"/&gt;
 *     &lt;enumeration value="CHN"/&gt;
 *     &lt;enumeration value="CIV"/&gt;
 *     &lt;enumeration value="CMR"/&gt;
 *     &lt;enumeration value="COD"/&gt;
 *     &lt;enumeration value="COG"/&gt;
 *     &lt;enumeration value="COK"/&gt;
 *     &lt;enumeration value="COL"/&gt;
 *     &lt;enumeration value="COM"/&gt;
 *     &lt;enumeration value="CPT"/&gt;
 *     &lt;enumeration value="CPV"/&gt;
 *     &lt;enumeration value="CRI"/&gt;
 *     &lt;enumeration value="CUB"/&gt;
 *     &lt;enumeration value="CUW"/&gt;
 *     &lt;enumeration value="CXR"/&gt;
 *     &lt;enumeration value="CYM"/&gt;
 *     &lt;enumeration value="CYP"/&gt;
 *     &lt;enumeration value="CZE"/&gt;
 *     &lt;enumeration value="DEU"/&gt;
 *     &lt;enumeration value="DGA"/&gt;
 *     &lt;enumeration value="DJI"/&gt;
 *     &lt;enumeration value="DMA"/&gt;
 *     &lt;enumeration value="DNK"/&gt;
 *     &lt;enumeration value="DOM"/&gt;
 *     &lt;enumeration value="DZA"/&gt;
 *     &lt;enumeration value="ECU"/&gt;
 *     &lt;enumeration value="EGY"/&gt;
 *     &lt;enumeration value="ERI"/&gt;
 *     &lt;enumeration value="ESH"/&gt;
 *     &lt;enumeration value="ESP"/&gt;
 *     &lt;enumeration value="EST"/&gt;
 *     &lt;enumeration value="ETH"/&gt;
 *     &lt;enumeration value="FIN"/&gt;
 *     &lt;enumeration value="FJI"/&gt;
 *     &lt;enumeration value="FLK"/&gt;
 *     &lt;enumeration value="FRA"/&gt;
 *     &lt;enumeration value="FRO"/&gt;
 *     &lt;enumeration value="FSM"/&gt;
 *     &lt;enumeration value="GAB"/&gt;
 *     &lt;enumeration value="GBR"/&gt;
 *     &lt;enumeration value="GEO"/&gt;
 *     &lt;enumeration value="GGY"/&gt;
 *     &lt;enumeration value="GHA"/&gt;
 *     &lt;enumeration value="GIB"/&gt;
 *     &lt;enumeration value="GIN"/&gt;
 *     &lt;enumeration value="GLP"/&gt;
 *     &lt;enumeration value="GMB"/&gt;
 *     &lt;enumeration value="GNB"/&gt;
 *     &lt;enumeration value="GNQ"/&gt;
 *     &lt;enumeration value="GRC"/&gt;
 *     &lt;enumeration value="GRD"/&gt;
 *     &lt;enumeration value="GRL"/&gt;
 *     &lt;enumeration value="GTM"/&gt;
 *     &lt;enumeration value="GUF"/&gt;
 *     &lt;enumeration value="GUM"/&gt;
 *     &lt;enumeration value="GUY"/&gt;
 *     &lt;enumeration value="HKG"/&gt;
 *     &lt;enumeration value="HMD"/&gt;
 *     &lt;enumeration value="HND"/&gt;
 *     &lt;enumeration value="HRV"/&gt;
 *     &lt;enumeration value="HTI"/&gt;
 *     &lt;enumeration value="HUN"/&gt;
 *     &lt;enumeration value="IDN"/&gt;
 *     &lt;enumeration value="IMN"/&gt;
 *     &lt;enumeration value="IND"/&gt;
 *     &lt;enumeration value="IOT"/&gt;
 *     &lt;enumeration value="IRL"/&gt;
 *     &lt;enumeration value="IRN"/&gt;
 *     &lt;enumeration value="IRQ"/&gt;
 *     &lt;enumeration value="ISL"/&gt;
 *     &lt;enumeration value="ISR"/&gt;
 *     &lt;enumeration value="ITA"/&gt;
 *     &lt;enumeration value="JAM"/&gt;
 *     &lt;enumeration value="JEY"/&gt;
 *     &lt;enumeration value="JOR"/&gt;
 *     &lt;enumeration value="JPN"/&gt;
 *     &lt;enumeration value="KAZ"/&gt;
 *     &lt;enumeration value="KEN"/&gt;
 *     &lt;enumeration value="KGZ"/&gt;
 *     &lt;enumeration value="KHM"/&gt;
 *     &lt;enumeration value="KIR"/&gt;
 *     &lt;enumeration value="KNA"/&gt;
 *     &lt;enumeration value="KOR"/&gt;
 *     &lt;enumeration value="KWT"/&gt;
 *     &lt;enumeration value="LAO"/&gt;
 *     &lt;enumeration value="LBN"/&gt;
 *     &lt;enumeration value="LBR"/&gt;
 *     &lt;enumeration value="LBY"/&gt;
 *     &lt;enumeration value="LCA"/&gt;
 *     &lt;enumeration value="LIE"/&gt;
 *     &lt;enumeration value="LKA"/&gt;
 *     &lt;enumeration value="LSO"/&gt;
 *     &lt;enumeration value="LTU"/&gt;
 *     &lt;enumeration value="LUX"/&gt;
 *     &lt;enumeration value="LVA"/&gt;
 *     &lt;enumeration value="MAC"/&gt;
 *     &lt;enumeration value="MAF"/&gt;
 *     &lt;enumeration value="MAR"/&gt;
 *     &lt;enumeration value="MCO"/&gt;
 *     &lt;enumeration value="MDA"/&gt;
 *     &lt;enumeration value="MDG"/&gt;
 *     &lt;enumeration value="MDV"/&gt;
 *     &lt;enumeration value="MEX"/&gt;
 *     &lt;enumeration value="MHL"/&gt;
 *     &lt;enumeration value="MKD"/&gt;
 *     &lt;enumeration value="MLI"/&gt;
 *     &lt;enumeration value="MLT"/&gt;
 *     &lt;enumeration value="MMR"/&gt;
 *     &lt;enumeration value="MNE"/&gt;
 *     &lt;enumeration value="MNG"/&gt;
 *     &lt;enumeration value="MNP"/&gt;
 *     &lt;enumeration value="MOZ"/&gt;
 *     &lt;enumeration value="MRT"/&gt;
 *     &lt;enumeration value="MSR"/&gt;
 *     &lt;enumeration value="MTQ"/&gt;
 *     &lt;enumeration value="MUS"/&gt;
 *     &lt;enumeration value="MWI"/&gt;
 *     &lt;enumeration value="MYS"/&gt;
 *     &lt;enumeration value="MYT"/&gt;
 *     &lt;enumeration value="NAM"/&gt;
 *     &lt;enumeration value="NCL"/&gt;
 *     &lt;enumeration value="NER"/&gt;
 *     &lt;enumeration value="NFK"/&gt;
 *     &lt;enumeration value="NGA"/&gt;
 *     &lt;enumeration value="NIC"/&gt;
 *     &lt;enumeration value="NIU"/&gt;
 *     &lt;enumeration value="NLD"/&gt;
 *     &lt;enumeration value="NOR"/&gt;
 *     &lt;enumeration value="NPL"/&gt;
 *     &lt;enumeration value="NRU"/&gt;
 *     &lt;enumeration value="NZL"/&gt;
 *     &lt;enumeration value="OMN"/&gt;
 *     &lt;enumeration value="PAK"/&gt;
 *     &lt;enumeration value="PAN"/&gt;
 *     &lt;enumeration value="PCN"/&gt;
 *     &lt;enumeration value="PER"/&gt;
 *     &lt;enumeration value="PHL"/&gt;
 *     &lt;enumeration value="PLW"/&gt;
 *     &lt;enumeration value="PNG"/&gt;
 *     &lt;enumeration value="POL"/&gt;
 *     &lt;enumeration value="PRI"/&gt;
 *     &lt;enumeration value="PRK"/&gt;
 *     &lt;enumeration value="PRT"/&gt;
 *     &lt;enumeration value="PRY"/&gt;
 *     &lt;enumeration value="PYF"/&gt;
 *     &lt;enumeration value="QAT"/&gt;
 *     &lt;enumeration value="REU"/&gt;
 *     &lt;enumeration value="ROU"/&gt;
 *     &lt;enumeration value="RUS"/&gt;
 *     &lt;enumeration value="RWA"/&gt;
 *     &lt;enumeration value="SAU"/&gt;
 *     &lt;enumeration value="SDN"/&gt;
 *     &lt;enumeration value="SEN"/&gt;
 *     &lt;enumeration value="SGP"/&gt;
 *     &lt;enumeration value="SGS"/&gt;
 *     &lt;enumeration value="SHN"/&gt;
 *     &lt;enumeration value="SLB"/&gt;
 *     &lt;enumeration value="SLE"/&gt;
 *     &lt;enumeration value="SLV"/&gt;
 *     &lt;enumeration value="SMR"/&gt;
 *     &lt;enumeration value="SOM"/&gt;
 *     &lt;enumeration value="SPM"/&gt;
 *     &lt;enumeration value="SRB"/&gt;
 *     &lt;enumeration value="SSD"/&gt;
 *     &lt;enumeration value="STP"/&gt;
 *     &lt;enumeration value="SUR"/&gt;
 *     &lt;enumeration value="SVK"/&gt;
 *     &lt;enumeration value="SVN"/&gt;
 *     &lt;enumeration value="SWE"/&gt;
 *     &lt;enumeration value="SWZ"/&gt;
 *     &lt;enumeration value="SXM"/&gt;
 *     &lt;enumeration value="SYC"/&gt;
 *     &lt;enumeration value="SYR"/&gt;
 *     &lt;enumeration value="TCA"/&gt;
 *     &lt;enumeration value="TCD"/&gt;
 *     &lt;enumeration value="TGO"/&gt;
 *     &lt;enumeration value="THA"/&gt;
 *     &lt;enumeration value="TJK"/&gt;
 *     &lt;enumeration value="TKL"/&gt;
 *     &lt;enumeration value="TKM"/&gt;
 *     &lt;enumeration value="TLS"/&gt;
 *     &lt;enumeration value="TON"/&gt;
 *     &lt;enumeration value="TTO"/&gt;
 *     &lt;enumeration value="TUN"/&gt;
 *     &lt;enumeration value="TUR"/&gt;
 *     &lt;enumeration value="TUV"/&gt;
 *     &lt;enumeration value="TWN"/&gt;
 *     &lt;enumeration value="TZA"/&gt;
 *     &lt;enumeration value="UGA"/&gt;
 *     &lt;enumeration value="UKR"/&gt;
 *     &lt;enumeration value="URY"/&gt;
 *     &lt;enumeration value="USA"/&gt;
 *     &lt;enumeration value="UZB"/&gt;
 *     &lt;enumeration value="VAT"/&gt;
 *     &lt;enumeration value="VCT"/&gt;
 *     &lt;enumeration value="VEN"/&gt;
 *     &lt;enumeration value="VGB"/&gt;
 *     &lt;enumeration value="VIR"/&gt;
 *     &lt;enumeration value="VNM"/&gt;
 *     &lt;enumeration value="VUT"/&gt;
 *     &lt;enumeration value="WLF"/&gt;
 *     &lt;enumeration value="WSM"/&gt;
 *     &lt;enumeration value="XAC"/&gt;
 *     &lt;enumeration value="XAZ"/&gt;
 *     &lt;enumeration value="XBI"/&gt;
 *     &lt;enumeration value="XBK"/&gt;
 *     &lt;enumeration value="XCR"/&gt;
 *     &lt;enumeration value="XCS"/&gt;
 *     &lt;enumeration value="XCY"/&gt;
 *     &lt;enumeration value="XEU"/&gt;
 *     &lt;enumeration value="XGL"/&gt;
 *     &lt;enumeration value="XGZ"/&gt;
 *     &lt;enumeration value="XHO"/&gt;
 *     &lt;enumeration value="XJA"/&gt;
 *     &lt;enumeration value="XJM"/&gt;
 *     &lt;enumeration value="XJN"/&gt;
 *     &lt;enumeration value="XJV"/&gt;
 *     &lt;enumeration value="XKM"/&gt;
 *     &lt;enumeration value="XKN"/&gt;
 *     &lt;enumeration value="XKR"/&gt;
 *     &lt;enumeration value="XKS"/&gt;
 *     &lt;enumeration value="XMW"/&gt;
 *     &lt;enumeration value="XNV"/&gt;
 *     &lt;enumeration value="XPL"/&gt;
 *     &lt;enumeration value="XPR"/&gt;
 *     &lt;enumeration value="XQZ"/&gt;
 *     &lt;enumeration value="XSP"/&gt;
 *     &lt;enumeration value="XSV"/&gt;
 *     &lt;enumeration value="XTR"/&gt;
 *     &lt;enumeration value="XWB"/&gt;
 *     &lt;enumeration value="XWK"/&gt;
 *     &lt;enumeration value="XXD"/&gt;
 *     &lt;enumeration value="YEM"/&gt;
 *     &lt;enumeration value="ZAF"/&gt;
 *     &lt;enumeration value="ZMB"/&gt;
 *     &lt;enumeration value="ZWE"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "CountryAlpha3CodeSimpleType", namespace = "http://release.niem.gov/niem/codes/genc/5.0/")
@XmlEnum
public enum CountryAlpha3CodeSimpleType {


    /**
     * ARUBA
     * 
     */
    ABW("ABW"),

    /**
     * AFGHANISTAN
     * 
     */
    AFG("AFG"),

    /**
     * ANGOLA
     * 
     */
    AGO("AGO"),

    /**
     * ANGUILLA
     * 
     */
    AIA("AIA"),

    /**
     * ALBANIA
     * 
     */
    ALB("ALB"),

    /**
     * ANDORRA
     * 
     */
    AND("AND"),

    /**
     * UNITED ARAB EMIRATES
     * 
     */
    ARE("ARE"),

    /**
     * ARGENTINA
     * 
     */
    ARG("ARG"),

    /**
     * ARMENIA
     * 
     */
    ARM("ARM"),

    /**
     * AMERICAN SAMOA
     * 
     */
    ASM("ASM"),

    /**
     * ANTARCTICA
     * 
     */
    ATA("ATA"),

    /**
     * FRENCH SOUTHERN AND ANTARCTIC LANDS
     * 
     */
    ATF("ATF"),

    /**
     * ANTIGUA AND BARBUDA
     * 
     */
    ATG("ATG"),

    /**
     * AUSTRALIA
     * 
     */
    AUS("AUS"),

    /**
     * AUSTRIA
     * 
     */
    AUT("AUT"),

    /**
     * UNKNOWN
     * 
     */
    @XmlEnumValue("AX1")
    AX_1("AX1"),

    /**
     * GUANTANAMO BAY NAVAL BASE
     * 
     */
    @XmlEnumValue("AX2")
    AX_2("AX2"),

    /**
     * ENTITY 6
     * 
     */
    @XmlEnumValue("AX3")
    AX_3("AX3"),

    /**
     * AZERBAIJAN
     * 
     */
    AZE("AZE"),

    /**
     * BURUNDI
     * 
     */
    BDI("BDI"),

    /**
     * BELGIUM
     * 
     */
    BEL("BEL"),

    /**
     * BENIN
     * 
     */
    BEN("BEN"),

    /**
     * BONAIRE, SINT EUSTATIUS, AND SABA
     * 
     */
    BES("BES"),

    /**
     * BURKINA FASO
     * 
     */
    BFA("BFA"),

    /**
     * BANGLADESH
     * 
     */
    BGD("BGD"),

    /**
     * BULGARIA
     * 
     */
    BGR("BGR"),

    /**
     * BAHRAIN
     * 
     */
    BHR("BHR"),

    /**
     * BAHAMAS, THE
     * 
     */
    BHS("BHS"),

    /**
     * BOSNIA AND HERZEGOVINA
     * 
     */
    BIH("BIH"),

    /**
     * SAINT BARTHELEMY
     * 
     */
    BLM("BLM"),

    /**
     * BELARUS
     * 
     */
    BLR("BLR"),

    /**
     * BELIZE
     * 
     */
    BLZ("BLZ"),

    /**
     * BERMUDA
     * 
     */
    BMU("BMU"),

    /**
     * BOLIVIA
     * 
     */
    BOL("BOL"),

    /**
     * BRAZIL
     * 
     */
    BRA("BRA"),

    /**
     * BARBADOS
     * 
     */
    BRB("BRB"),

    /**
     * BRUNEI
     * 
     */
    BRN("BRN"),

    /**
     * BHUTAN
     * 
     */
    BTN("BTN"),

    /**
     * BOUVET ISLAND
     * 
     */
    BVT("BVT"),

    /**
     * BOTSWANA
     * 
     */
    BWA("BWA"),

    /**
     * CENTRAL AFRICAN REPUBLIC
     * 
     */
    CAF("CAF"),

    /**
     * CANADA
     * 
     */
    CAN("CAN"),

    /**
     * COCOS (KEELING) ISLANDS
     * 
     */
    CCK("CCK"),

    /**
     * SWITZERLAND
     * 
     */
    CHE("CHE"),

    /**
     * CHILE
     * 
     */
    CHL("CHL"),

    /**
     * CHINA
     * 
     */
    CHN("CHN"),

    /**
     * CÔTE D’IVOIRE
     * 
     */
    CIV("CIV"),

    /**
     * CAMEROON
     * 
     */
    CMR("CMR"),

    /**
     * CONGO (KINSHASA)
     * 
     */
    COD("COD"),

    /**
     * CONGO (BRAZZAVILLE)
     * 
     */
    COG("COG"),

    /**
     * COOK ISLANDS
     * 
     */
    COK("COK"),

    /**
     * COLOMBIA
     * 
     */
    COL("COL"),

    /**
     * COMOROS
     * 
     */
    COM("COM"),

    /**
     * CLIPPERTON ISLAND
     * 
     */
    CPT("CPT"),

    /**
     * CABO VERDE
     * 
     */
    CPV("CPV"),

    /**
     * COSTA RICA
     * 
     */
    CRI("CRI"),

    /**
     * CUBA
     * 
     */
    CUB("CUB"),

    /**
     * CURAÇAO
     * 
     */
    CUW("CUW"),

    /**
     * CHRISTMAS ISLAND
     * 
     */
    CXR("CXR"),

    /**
     * CAYMAN ISLANDS
     * 
     */
    CYM("CYM"),

    /**
     * CYPRUS
     * 
     */
    CYP("CYP"),

    /**
     * CZECHIA
     * 
     */
    CZE("CZE"),

    /**
     * GERMANY
     * 
     */
    DEU("DEU"),

    /**
     * DIEGO GARCIA
     * 
     */
    DGA("DGA"),

    /**
     * DJIBOUTI
     * 
     */
    DJI("DJI"),

    /**
     * DOMINICA
     * 
     */
    DMA("DMA"),

    /**
     * DENMARK
     * 
     */
    DNK("DNK"),

    /**
     * DOMINICAN REPUBLIC
     * 
     */
    DOM("DOM"),

    /**
     * ALGERIA
     * 
     */
    DZA("DZA"),

    /**
     * ECUADOR
     * 
     */
    ECU("ECU"),

    /**
     * EGYPT
     * 
     */
    EGY("EGY"),

    /**
     * ERITREA
     * 
     */
    ERI("ERI"),

    /**
     * WESTERN SAHARA
     * 
     */
    ESH("ESH"),

    /**
     * SPAIN
     * 
     */
    ESP("ESP"),

    /**
     * ESTONIA
     * 
     */
    EST("EST"),

    /**
     * ETHIOPIA
     * 
     */
    ETH("ETH"),

    /**
     * FINLAND
     * 
     */
    FIN("FIN"),

    /**
     * FIJI
     * 
     */
    FJI("FJI"),

    /**
     * FALKLAND ISLANDS (ISLAS MALVINAS)
     * 
     */
    FLK("FLK"),

    /**
     * FRANCE
     * 
     */
    FRA("FRA"),

    /**
     * FAROE ISLANDS
     * 
     */
    FRO("FRO"),

    /**
     * MICRONESIA, FEDERATED STATES OF
     * 
     */
    FSM("FSM"),

    /**
     * GABON
     * 
     */
    GAB("GAB"),

    /**
     * UNITED KINGDOM
     * 
     */
    GBR("GBR"),

    /**
     * GEORGIA
     * 
     */
    GEO("GEO"),

    /**
     * GUERNSEY
     * 
     */
    GGY("GGY"),

    /**
     * GHANA
     * 
     */
    GHA("GHA"),

    /**
     * GIBRALTAR
     * 
     */
    GIB("GIB"),

    /**
     * GUINEA
     * 
     */
    GIN("GIN"),

    /**
     * GUADELOUPE
     * 
     */
    GLP("GLP"),

    /**
     * GAMBIA, THE
     * 
     */
    GMB("GMB"),

    /**
     * GUINEA-BISSAU
     * 
     */
    GNB("GNB"),

    /**
     * EQUATORIAL GUINEA
     * 
     */
    GNQ("GNQ"),

    /**
     * GREECE
     * 
     */
    GRC("GRC"),

    /**
     * GRENADA
     * 
     */
    GRD("GRD"),

    /**
     * GREENLAND
     * 
     */
    GRL("GRL"),

    /**
     * GUATEMALA
     * 
     */
    GTM("GTM"),

    /**
     * FRENCH GUIANA
     * 
     */
    GUF("GUF"),

    /**
     * GUAM
     * 
     */
    GUM("GUM"),

    /**
     * GUYANA
     * 
     */
    GUY("GUY"),

    /**
     * HONG KONG
     * 
     */
    HKG("HKG"),

    /**
     * HEARD ISLAND AND MCDONALD ISLANDS
     * 
     */
    HMD("HMD"),

    /**
     * HONDURAS
     * 
     */
    HND("HND"),

    /**
     * CROATIA
     * 
     */
    HRV("HRV"),

    /**
     * HAITI
     * 
     */
    HTI("HTI"),

    /**
     * HUNGARY
     * 
     */
    HUN("HUN"),

    /**
     * INDONESIA
     * 
     */
    IDN("IDN"),

    /**
     * ISLE OF MAN
     * 
     */
    IMN("IMN"),

    /**
     * INDIA
     * 
     */
    IND("IND"),

    /**
     * BRITISH INDIAN OCEAN TERRITORY
     * 
     */
    IOT("IOT"),

    /**
     * IRELAND
     * 
     */
    IRL("IRL"),

    /**
     * IRAN
     * 
     */
    IRN("IRN"),

    /**
     * IRAQ
     * 
     */
    IRQ("IRQ"),

    /**
     * ICELAND
     * 
     */
    ISL("ISL"),

    /**
     * ISRAEL
     * 
     */
    ISR("ISR"),

    /**
     * ITALY
     * 
     */
    ITA("ITA"),

    /**
     * JAMAICA
     * 
     */
    JAM("JAM"),

    /**
     * JERSEY
     * 
     */
    JEY("JEY"),

    /**
     * JORDAN
     * 
     */
    JOR("JOR"),

    /**
     * JAPAN
     * 
     */
    JPN("JPN"),

    /**
     * KAZAKHSTAN
     * 
     */
    KAZ("KAZ"),

    /**
     * KENYA
     * 
     */
    KEN("KEN"),

    /**
     * KYRGYZSTAN
     * 
     */
    KGZ("KGZ"),

    /**
     * CAMBODIA
     * 
     */
    KHM("KHM"),

    /**
     * KIRIBATI
     * 
     */
    KIR("KIR"),

    /**
     * SAINT KITTS AND NEVIS
     * 
     */
    KNA("KNA"),

    /**
     * KOREA, SOUTH
     * 
     */
    KOR("KOR"),

    /**
     * KUWAIT
     * 
     */
    KWT("KWT"),

    /**
     * LAOS
     * 
     */
    LAO("LAO"),

    /**
     * LEBANON
     * 
     */
    LBN("LBN"),

    /**
     * LIBERIA
     * 
     */
    LBR("LBR"),

    /**
     * LIBYA
     * 
     */
    LBY("LBY"),

    /**
     * SAINT LUCIA
     * 
     */
    LCA("LCA"),

    /**
     * LIECHTENSTEIN
     * 
     */
    LIE("LIE"),

    /**
     * SRI LANKA
     * 
     */
    LKA("LKA"),

    /**
     * LESOTHO
     * 
     */
    LSO("LSO"),

    /**
     * LITHUANIA
     * 
     */
    LTU("LTU"),

    /**
     * LUXEMBOURG
     * 
     */
    LUX("LUX"),

    /**
     * LATVIA
     * 
     */
    LVA("LVA"),

    /**
     * MACAU
     * 
     */
    MAC("MAC"),

    /**
     * SAINT MARTIN
     * 
     */
    MAF("MAF"),

    /**
     * MOROCCO
     * 
     */
    MAR("MAR"),

    /**
     * MONACO
     * 
     */
    MCO("MCO"),

    /**
     * MOLDOVA
     * 
     */
    MDA("MDA"),

    /**
     * MADAGASCAR
     * 
     */
    MDG("MDG"),

    /**
     * MALDIVES
     * 
     */
    MDV("MDV"),

    /**
     * MEXICO
     * 
     */
    MEX("MEX"),

    /**
     * MARSHALL ISLANDS
     * 
     */
    MHL("MHL"),

    /**
     * NORTH MACEDONIA
     * 
     */
    MKD("MKD"),

    /**
     * MALI
     * 
     */
    MLI("MLI"),

    /**
     * MALTA
     * 
     */
    MLT("MLT"),

    /**
     * BURMA
     * 
     */
    MMR("MMR"),

    /**
     * MONTENEGRO
     * 
     */
    MNE("MNE"),

    /**
     * MONGOLIA
     * 
     */
    MNG("MNG"),

    /**
     * NORTHERN MARIANA ISLANDS
     * 
     */
    MNP("MNP"),

    /**
     * MOZAMBIQUE
     * 
     */
    MOZ("MOZ"),

    /**
     * MAURITANIA
     * 
     */
    MRT("MRT"),

    /**
     * MONTSERRAT
     * 
     */
    MSR("MSR"),

    /**
     * MARTINIQUE
     * 
     */
    MTQ("MTQ"),

    /**
     * MAURITIUS
     * 
     */
    MUS("MUS"),

    /**
     * MALAWI
     * 
     */
    MWI("MWI"),

    /**
     * MALAYSIA
     * 
     */
    MYS("MYS"),

    /**
     * MAYOTTE
     * 
     */
    MYT("MYT"),

    /**
     * NAMIBIA
     * 
     */
    NAM("NAM"),

    /**
     * NEW CALEDONIA
     * 
     */
    NCL("NCL"),

    /**
     * NIGER
     * 
     */
    NER("NER"),

    /**
     * NORFOLK ISLAND
     * 
     */
    NFK("NFK"),

    /**
     * NIGERIA
     * 
     */
    NGA("NGA"),

    /**
     * NICARAGUA
     * 
     */
    NIC("NIC"),

    /**
     * NIUE
     * 
     */
    NIU("NIU"),

    /**
     * NETHERLANDS
     * 
     */
    NLD("NLD"),

    /**
     * NORWAY
     * 
     */
    NOR("NOR"),

    /**
     * NEPAL
     * 
     */
    NPL("NPL"),

    /**
     * NAURU
     * 
     */
    NRU("NRU"),

    /**
     * NEW ZEALAND
     * 
     */
    NZL("NZL"),

    /**
     * OMAN
     * 
     */
    OMN("OMN"),

    /**
     * PAKISTAN
     * 
     */
    PAK("PAK"),

    /**
     * PANAMA
     * 
     */
    PAN("PAN"),

    /**
     * PITCAIRN ISLANDS
     * 
     */
    PCN("PCN"),

    /**
     * PERU
     * 
     */
    PER("PER"),

    /**
     * PHILIPPINES
     * 
     */
    PHL("PHL"),

    /**
     * PALAU
     * 
     */
    PLW("PLW"),

    /**
     * PAPUA NEW GUINEA
     * 
     */
    PNG("PNG"),

    /**
     * POLAND
     * 
     */
    POL("POL"),

    /**
     * PUERTO RICO
     * 
     */
    PRI("PRI"),

    /**
     * KOREA, NORTH
     * 
     */
    PRK("PRK"),

    /**
     * PORTUGAL
     * 
     */
    PRT("PRT"),

    /**
     * PARAGUAY
     * 
     */
    PRY("PRY"),

    /**
     * FRENCH POLYNESIA
     * 
     */
    PYF("PYF"),

    /**
     * QATAR
     * 
     */
    QAT("QAT"),

    /**
     * REUNION
     * 
     */
    REU("REU"),

    /**
     * ROMANIA
     * 
     */
    ROU("ROU"),

    /**
     * RUSSIA
     * 
     */
    RUS("RUS"),

    /**
     * RWANDA
     * 
     */
    RWA("RWA"),

    /**
     * SAUDI ARABIA
     * 
     */
    SAU("SAU"),

    /**
     * SUDAN
     * 
     */
    SDN("SDN"),

    /**
     * SENEGAL
     * 
     */
    SEN("SEN"),

    /**
     * SINGAPORE
     * 
     */
    SGP("SGP"),

    /**
     * SOUTH GEORGIA AND SOUTH SANDWICH ISLANDS
     * 
     */
    SGS("SGS"),

    /**
     * SAINT HELENA, ASCENSION, AND TRISTAN DA CUNHA
     * 
     */
    SHN("SHN"),

    /**
     * SOLOMON ISLANDS
     * 
     */
    SLB("SLB"),

    /**
     * SIERRA LEONE
     * 
     */
    SLE("SLE"),

    /**
     * EL SALVADOR
     * 
     */
    SLV("SLV"),

    /**
     * SAN MARINO
     * 
     */
    SMR("SMR"),

    /**
     * SOMALIA
     * 
     */
    SOM("SOM"),

    /**
     * SAINT PIERRE AND MIQUELON
     * 
     */
    SPM("SPM"),

    /**
     * SERBIA
     * 
     */
    SRB("SRB"),

    /**
     * SOUTH SUDAN
     * 
     */
    SSD("SSD"),

    /**
     * SAO TOME AND PRINCIPE
     * 
     */
    STP("STP"),

    /**
     * SURINAME
     * 
     */
    SUR("SUR"),

    /**
     * SLOVAKIA
     * 
     */
    SVK("SVK"),

    /**
     * SLOVENIA
     * 
     */
    SVN("SVN"),

    /**
     * SWEDEN
     * 
     */
    SWE("SWE"),

    /**
     * ESWATINI
     * 
     */
    SWZ("SWZ"),

    /**
     * SINT MAARTEN
     * 
     */
    SXM("SXM"),

    /**
     * SEYCHELLES
     * 
     */
    SYC("SYC"),

    /**
     * SYRIA
     * 
     */
    SYR("SYR"),

    /**
     * TURKS AND CAICOS ISLANDS
     * 
     */
    TCA("TCA"),

    /**
     * CHAD
     * 
     */
    TCD("TCD"),

    /**
     * TOGO
     * 
     */
    TGO("TGO"),

    /**
     * THAILAND
     * 
     */
    THA("THA"),

    /**
     * TAJIKISTAN
     * 
     */
    TJK("TJK"),

    /**
     * TOKELAU
     * 
     */
    TKL("TKL"),

    /**
     * TURKMENISTAN
     * 
     */
    TKM("TKM"),

    /**
     * TIMOR-LESTE
     * 
     */
    TLS("TLS"),

    /**
     * TONGA
     * 
     */
    TON("TON"),

    /**
     * TRINIDAD AND TOBAGO
     * 
     */
    TTO("TTO"),

    /**
     * TUNISIA
     * 
     */
    TUN("TUN"),

    /**
     * TURKEY
     * 
     */
    TUR("TUR"),

    /**
     * TUVALU
     * 
     */
    TUV("TUV"),

    /**
     * TAIWAN
     * 
     */
    TWN("TWN"),

    /**
     * TANZANIA
     * 
     */
    TZA("TZA"),

    /**
     * UGANDA
     * 
     */
    UGA("UGA"),

    /**
     * UKRAINE
     * 
     */
    UKR("UKR"),

    /**
     * URUGUAY
     * 
     */
    URY("URY"),

    /**
     * UNITED STATES
     * 
     */
    USA("USA"),

    /**
     * UZBEKISTAN
     * 
     */
    UZB("UZB"),

    /**
     * VATICAN CITY
     * 
     */
    VAT("VAT"),

    /**
     * SAINT VINCENT AND THE GRENADINES
     * 
     */
    VCT("VCT"),

    /**
     * VENEZUELA
     * 
     */
    VEN("VEN"),

    /**
     * VIRGIN ISLANDS, BRITISH
     * 
     */
    VGB("VGB"),

    /**
     * VIRGIN ISLANDS, U.S.
     * 
     */
    VIR("VIR"),

    /**
     * VIETNAM
     * 
     */
    VNM("VNM"),

    /**
     * VANUATU
     * 
     */
    VUT("VUT"),

    /**
     * WALLIS AND FUTUNA
     * 
     */
    WLF("WLF"),

    /**
     * SAMOA
     * 
     */
    WSM("WSM"),

    /**
     * ASHMORE AND CARTIER ISLANDS
     * 
     */
    XAC("XAC"),

    /**
     * ENTITY 1
     * 
     */
    XAZ("XAZ"),

    /**
     * BASSAS DA INDIA
     * 
     */
    XBI("XBI"),

    /**
     * BAKER ISLAND
     * 
     */
    XBK("XBK"),

    /**
     * ENTITY 2
     * 
     */
    XCR("XCR"),

    /**
     * CORAL SEA ISLANDS
     * 
     */
    XCS("XCS"),

    /**
     * ENTITY 3
     * 
     */
    XCY("XCY"),

    /**
     * EUROPA ISLAND
     * 
     */
    XEU("XEU"),

    /**
     * GLORIOSO ISLANDS
     * 
     */
    XGL("XGL"),

    /**
     * GAZA STRIP
     * 
     */
    XGZ("XGZ"),

    /**
     * HOWLAND ISLAND
     * 
     */
    XHO("XHO"),

    /**
     * JOHNSTON ATOLL
     * 
     */
    XJA("XJA"),

    /**
     * JAN MAYEN
     * 
     */
    XJM("XJM"),

    /**
     * JUAN DE NOVA ISLAND
     * 
     */
    XJN("XJN"),

    /**
     * JARVIS ISLAND
     * 
     */
    XJV("XJV"),

    /**
     * ENTITY 4
     * 
     */
    XKM("XKM"),

    /**
     * ENTITY 5
     * 
     */
    XKN("XKN"),

    /**
     * KINGMAN REEF
     * 
     */
    XKR("XKR"),

    /**
     * KOSOVO
     * 
     */
    XKS("XKS"),

    /**
     * MIDWAY ISLANDS
     * 
     */
    XMW("XMW"),

    /**
     * NAVASSA ISLAND
     * 
     */
    XNV("XNV"),

    /**
     * PALMYRA ATOLL
     * 
     */
    XPL("XPL"),

    /**
     * PARACEL ISLANDS
     * 
     */
    XPR("XPR"),

    /**
     * AKROTIRI
     * 
     */
    XQZ("XQZ"),

    /**
     * SPRATLY ISLANDS
     * 
     */
    XSP("XSP"),

    /**
     * SVALBARD
     * 
     */
    XSV("XSV"),

    /**
     * TROMELIN ISLAND
     * 
     */
    XTR("XTR"),

    /**
     * WEST BANK
     * 
     */
    XWB("XWB"),

    /**
     * WAKE ISLAND
     * 
     */
    XWK("XWK"),

    /**
     * DHEKELIA
     * 
     */
    XXD("XXD"),

    /**
     * YEMEN
     * 
     */
    YEM("YEM"),

    /**
     * SOUTH AFRICA
     * 
     */
    ZAF("ZAF"),

    /**
     * ZAMBIA
     * 
     */
    ZMB("ZMB"),

    /**
     * ZIMBABWE
     * 
     */
    ZWE("ZWE");
    private final String value;

    CountryAlpha3CodeSimpleType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CountryAlpha3CodeSimpleType fromValue(String v) {
        for (CountryAlpha3CodeSimpleType c: CountryAlpha3CodeSimpleType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
