//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.27 at 03:48:01 PM EST 
//


package gov.niem.codes.aamva_d20;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DriverLicensePermitEndorsementCodeSimpleType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DriverLicensePermitEndorsementCodeSimpleType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="L"/&gt;
 *     &lt;enumeration value="N"/&gt;
 *     &lt;enumeration value="O"/&gt;
 *     &lt;enumeration value="P"/&gt;
 *     &lt;enumeration value="S"/&gt;
 *     &lt;enumeration value="T"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "DriverLicensePermitEndorsementCodeSimpleType", namespace = "http://release.niem.gov/niem/codes/aamva_d20/5.0/")
@XmlEnum
public enum DriverLicensePermitEndorsementCodeSimpleType {


    /**
     * Motorcycle
     * 
     */
    L,

    /**
     * Tank
     * 
     */
    N,

    /**
     * Other
     * 
     */
    O,

    /**
     * Passenger
     * 
     */
    P,

    /**
     * School and Passenger Bus
     * 
     */
    S,

    /**
     * Doubles/Triples
     * 
     */
    T;

    public String value() {
        return name();
    }

    public static DriverLicensePermitEndorsementCodeSimpleType fromValue(String v) {
        return valueOf(v);
    }

}
