//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.27 at 04:09:22 PM EST 
//


package gov.niem.codes.aamva_d20;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.niem.codes.aamva_d20 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.niem.codes.aamva_d20
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DriverLicenseClassCodeType }
     * 
     */
    public DriverLicenseClassCodeType createDriverLicenseClassCodeType() {
        return new DriverLicenseClassCodeType();
    }

    /**
     * Create an instance of {@link DriverLicensePermitEndorsementCodeType }
     * 
     */
    public DriverLicensePermitEndorsementCodeType createDriverLicensePermitEndorsementCodeType() {
        return new DriverLicensePermitEndorsementCodeType();
    }

    /**
     * Create an instance of {@link DrivingPermitRestrictionCodeType }
     * 
     */
    public DrivingPermitRestrictionCodeType createDrivingPermitRestrictionCodeType() {
        return new DrivingPermitRestrictionCodeType();
    }

    /**
     * Create an instance of {@link DrivingStatusCodeType }
     * 
     */
    public DrivingStatusCodeType createDrivingStatusCodeType() {
        return new DrivingStatusCodeType();
    }

}
