//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.27 at 04:09:22 PM EST 
//


package gov.niem.core;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import gov.niem.domains.jxdm.BirthType;
import gov.niem.domains.jxdm.ConvictionType;
import gov.niem.domains.jxdm.DriverLicenseWithdrawalType;
import gov.niem.domains.jxdm.PersonDeathType;
import gov.niem.domains.jxdm.PleaType;
import gov.niem.domains.jxdm.SanctionType;
import gov.niem.domains.jxdm.SentenceType;
import gov.niem.domains.jxdm.VerdictType;
import gov.niem.utility.structures.ObjectType;


/**
 * A data type for a single or set of related actions, events, or process steps.
 * 
 * <p>Java class for ActivityType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ActivityType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://release.niem.gov/niem/structures/5.0/}ObjectType"&gt;
 *       &lt;anyAttribute processContents='lax' namespace='urn:us:gov:ic:ntk urn:us:gov:ic:ism'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ActivityType", namespace = "http://release.niem.gov/niem/niem-core/5.0/")
@XmlSeeAlso({
    ConvictionType.class,
    PleaType.class,
    SanctionType.class,
    SentenceType.class,
    VerdictType.class,
    DriverLicenseWithdrawalType.class,
    BirthType.class,
    PersonDeathType.class,
    IncidentType.class
})
public class ActivityType
    extends ObjectType
{


}
