//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.27 at 03:48:01 PM EST 
//


package gov.niem.core;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import gov.niem.adapters.xs.AnyURI;
import gov.niem.adapters.xs.Boolean;
import gov.niem.adapters.xs.String;
import gov.niem.utility.structures.ObjectType;


/**
 * A data type for a paper or electronic document.
 * 
 * <p>Java class for DocumentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DocumentType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://release.niem.gov/niem/structures/5.0/}ObjectType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentApprovedIndicator" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentAuthor" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentCategoryAbstract" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentCategoryDescriptionText" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentContentAbstract" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentContentListText" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentContributor" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentCopyrightIndicator" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentCountry" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentCoverageAbstract" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentCreationDate" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentDescriptionText" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentDispositionAuthorityName" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentDispositionInstructionText" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentDisputedIndicator" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentDisputedReasonAbstract" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentEffectiveDate" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentEntrySubmitter" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentEUDataPrivacyIndicator" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentExpirationDate" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentFileControlID" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentFiledDate" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentFileExtensionText" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentFileName" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentFormatCategoryAbstract" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentFormatAbstract" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentGroupID" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentIdentification" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentInformationCutOffDate" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentIntelligenceCategoryAbstract" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentIssuanceLocation" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentIssueDate" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentKeywordAbstract" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentLanguage" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentLastModifiedDate" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentLocation" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentLocationURI" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentManagementCyclePeriodText" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentOtherRecipient" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentPermanentRecordIndicator" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentPhysicalMediumCategoryAbstract" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentPhysicalMediumText" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentPostDate" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentPrivacyActIndicator" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentPublicationDate" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentReceivedDate" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentRecipient" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentRelatedResourceText" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentRightsText" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentSensitivityAbstract" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentSequenceID" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentSoftware" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentSource" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentSourceText" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentStatus" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentStatusCategoryAbstract" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentSubjectAbstract" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentSubmissionAmount" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentSubmitter" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentSummaryText" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentSupplementalMarkingText" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentTitleAlternativeText" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentTitleText" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentVitalIndicator" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}DocumentAugmentationPoint" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;anyAttribute processContents='lax' namespace='urn:us:gov:ic:ntk urn:us:gov:ic:ism'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DocumentType", namespace = "http://release.niem.gov/niem/niem-core/5.0/", propOrder = {
    "documentApprovedIndicator",
    "documentAuthor",
    "documentCategoryAbstract",
    "documentCategoryDescriptionText",
    "documentContentAbstract",
    "documentContentListText",
    "documentContributor",
    "documentCopyrightIndicator",
    "documentCountry",
    "documentCoverageAbstract",
    "documentCreationDate",
    "documentDescriptionText",
    "documentDispositionAuthorityName",
    "documentDispositionInstructionText",
    "documentDisputedIndicator",
    "documentDisputedReasonAbstract",
    "documentEffectiveDate",
    "documentEntrySubmitter",
    "documentEUDataPrivacyIndicator",
    "documentExpirationDate",
    "documentFileControlID",
    "documentFiledDate",
    "documentFileExtensionText",
    "documentFileName",
    "documentFormatCategoryAbstract",
    "documentFormatAbstract",
    "documentGroupID",
    "documentIdentification",
    "documentInformationCutOffDate",
    "documentIntelligenceCategoryAbstract",
    "documentIssuanceLocation",
    "documentIssueDate",
    "documentKeywordAbstract",
    "documentLanguage",
    "documentLastModifiedDate",
    "documentLocation",
    "documentLocationURI",
    "documentManagementCyclePeriodText",
    "documentOtherRecipient",
    "documentPermanentRecordIndicator",
    "documentPhysicalMediumCategoryAbstract",
    "documentPhysicalMediumText",
    "documentPostDate",
    "documentPrivacyActIndicator",
    "documentPublicationDate",
    "documentReceivedDate",
    "documentRecipient",
    "documentRelatedResourceText",
    "documentRightsText",
    "documentSensitivityAbstract",
    "documentSequenceID",
    "documentSoftware",
    "documentSource",
    "documentSourceText",
    "documentStatus",
    "documentStatusCategoryAbstract",
    "documentSubjectAbstract",
    "documentSubmissionAmount",
    "documentSubmitter",
    "documentSummaryText",
    "documentSupplementalMarkingText",
    "documentTitleAlternativeText",
    "documentTitleText",
    "documentVitalIndicator",
    "documentAugmentationPoint"
})
public class DocumentType
    extends ObjectType
{

    @XmlElement(name = "DocumentApprovedIndicator", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<Boolean> documentApprovedIndicator;
    @XmlElement(name = "DocumentAuthor", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<EntityType> documentAuthor;
    @XmlElement(name = "DocumentCategoryAbstract", namespace = "http://release.niem.gov/niem/niem-core/5.0/")
    protected List<Object> documentCategoryAbstract;
    @XmlElement(name = "DocumentCategoryDescriptionText", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<TextType> documentCategoryDescriptionText;
    @XmlElement(name = "DocumentContentAbstract", namespace = "http://release.niem.gov/niem/niem-core/5.0/")
    protected List<Object> documentContentAbstract;
    @XmlElement(name = "DocumentContentListText", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<TextType> documentContentListText;
    @XmlElement(name = "DocumentContributor", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<EntityType> documentContributor;
    @XmlElement(name = "DocumentCopyrightIndicator", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<Boolean> documentCopyrightIndicator;
    @XmlElement(name = "DocumentCountry", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<CountryType> documentCountry;
    @XmlElement(name = "DocumentCoverageAbstract", namespace = "http://release.niem.gov/niem/niem-core/5.0/")
    protected List<Object> documentCoverageAbstract;
    @XmlElement(name = "DocumentCreationDate", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<DateType> documentCreationDate;
    @XmlElement(name = "DocumentDescriptionText", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<TextType> documentDescriptionText;
    @XmlElement(name = "DocumentDispositionAuthorityName", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<TextType> documentDispositionAuthorityName;
    @XmlElement(name = "DocumentDispositionInstructionText", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<TextType> documentDispositionInstructionText;
    @XmlElement(name = "DocumentDisputedIndicator", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<Boolean> documentDisputedIndicator;
    @XmlElement(name = "DocumentDisputedReasonAbstract", namespace = "http://release.niem.gov/niem/niem-core/5.0/")
    protected List<Object> documentDisputedReasonAbstract;
    @XmlElement(name = "DocumentEffectiveDate", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<DateType> documentEffectiveDate;
    @XmlElement(name = "DocumentEntrySubmitter", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<PersonType> documentEntrySubmitter;
    @XmlElement(name = "DocumentEUDataPrivacyIndicator", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<Boolean> documentEUDataPrivacyIndicator;
    @XmlElement(name = "DocumentExpirationDate", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<DateType> documentExpirationDate;
    @XmlElement(name = "DocumentFileControlID", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<String> documentFileControlID;
    @XmlElement(name = "DocumentFiledDate", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<DateType> documentFiledDate;
    @XmlElement(name = "DocumentFileExtensionText", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<TextType> documentFileExtensionText;
    @XmlElement(name = "DocumentFileName", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<TextType> documentFileName;
    @XmlElement(name = "DocumentFormatCategoryAbstract", namespace = "http://release.niem.gov/niem/niem-core/5.0/")
    protected List<Object> documentFormatCategoryAbstract;
    @XmlElement(name = "DocumentFormatAbstract", namespace = "http://release.niem.gov/niem/niem-core/5.0/")
    protected List<Object> documentFormatAbstract;
    @XmlElement(name = "DocumentGroupID", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<String> documentGroupID;
    @XmlElement(name = "DocumentIdentification", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<IdentificationType> documentIdentification;
    @XmlElement(name = "DocumentInformationCutOffDate", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<DateType> documentInformationCutOffDate;
    @XmlElement(name = "DocumentIntelligenceCategoryAbstract", namespace = "http://release.niem.gov/niem/niem-core/5.0/")
    protected List<Object> documentIntelligenceCategoryAbstract;
    @XmlElement(name = "DocumentIssuanceLocation", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<LocationType> documentIssuanceLocation;
    @XmlElement(name = "DocumentIssueDate", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<DateType> documentIssueDate;
    @XmlElement(name = "DocumentKeywordAbstract", namespace = "http://release.niem.gov/niem/niem-core/5.0/")
    protected List<Object> documentKeywordAbstract;
    @XmlElement(name = "DocumentLanguage", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<LanguageType> documentLanguage;
    @XmlElement(name = "DocumentLastModifiedDate", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<DateType> documentLastModifiedDate;
    @XmlElement(name = "DocumentLocation", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<LocationType> documentLocation;
    @XmlElement(name = "DocumentLocationURI", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<AnyURI> documentLocationURI;
    @XmlElement(name = "DocumentManagementCyclePeriodText", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<TextType> documentManagementCyclePeriodText;
    @XmlElement(name = "DocumentOtherRecipient", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<EntityType> documentOtherRecipient;
    @XmlElement(name = "DocumentPermanentRecordIndicator", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<Boolean> documentPermanentRecordIndicator;
    @XmlElement(name = "DocumentPhysicalMediumCategoryAbstract", namespace = "http://release.niem.gov/niem/niem-core/5.0/")
    protected List<Object> documentPhysicalMediumCategoryAbstract;
    @XmlElement(name = "DocumentPhysicalMediumText", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<TextType> documentPhysicalMediumText;
    @XmlElement(name = "DocumentPostDate", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<DateType> documentPostDate;
    @XmlElement(name = "DocumentPrivacyActIndicator", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<Boolean> documentPrivacyActIndicator;
    @XmlElement(name = "DocumentPublicationDate", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<DateType> documentPublicationDate;
    @XmlElement(name = "DocumentReceivedDate", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<DateType> documentReceivedDate;
    @XmlElement(name = "DocumentRecipient", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<EntityType> documentRecipient;
    @XmlElement(name = "DocumentRelatedResourceText", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<TextType> documentRelatedResourceText;
    @XmlElement(name = "DocumentRightsText", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<TextType> documentRightsText;
    @XmlElement(name = "DocumentSensitivityAbstract", namespace = "http://release.niem.gov/niem/niem-core/5.0/")
    protected List<Object> documentSensitivityAbstract;
    @XmlElement(name = "DocumentSequenceID", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<String> documentSequenceID;
    @XmlElement(name = "DocumentSoftware", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<SoftwareType> documentSoftware;
    @XmlElement(name = "DocumentSource", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<EntityType> documentSource;
    @XmlElement(name = "DocumentSourceText", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<TextType> documentSourceText;
    @XmlElement(name = "DocumentStatus", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<StatusType> documentStatus;
    @XmlElement(name = "DocumentStatusCategoryAbstract", namespace = "http://release.niem.gov/niem/niem-core/5.0/")
    protected List<Object> documentStatusCategoryAbstract;
    @XmlElement(name = "DocumentSubjectAbstract", namespace = "http://release.niem.gov/niem/niem-core/5.0/")
    protected List<Object> documentSubjectAbstract;
    @XmlElement(name = "DocumentSubmissionAmount", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<AmountType> documentSubmissionAmount;
    @XmlElement(name = "DocumentSubmitter", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<EntityType> documentSubmitter;
    @XmlElement(name = "DocumentSummaryText", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<TextType> documentSummaryText;
    @XmlElement(name = "DocumentSupplementalMarkingText", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<TextType> documentSupplementalMarkingText;
    @XmlElement(name = "DocumentTitleAlternativeText", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<TextType> documentTitleAlternativeText;
    @XmlElement(name = "DocumentTitleText", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<TextType> documentTitleText;
    @XmlElement(name = "DocumentVitalIndicator", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<Boolean> documentVitalIndicator;
    @XmlElement(name = "DocumentAugmentationPoint", namespace = "http://release.niem.gov/niem/niem-core/5.0/")
    protected List<Object> documentAugmentationPoint;

    /**
     * Gets the value of the documentApprovedIndicator property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentApprovedIndicator property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentApprovedIndicator().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Boolean }
     * 
     * 
     */
    public List<Boolean> getDocumentApprovedIndicator() {
        if (documentApprovedIndicator == null) {
            documentApprovedIndicator = new ArrayList<Boolean>();
        }
        return this.documentApprovedIndicator;
    }

    /**
     * Gets the value of the documentAuthor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentAuthor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentAuthor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EntityType }
     * 
     * 
     */
    public List<EntityType> getDocumentAuthor() {
        if (documentAuthor == null) {
            documentAuthor = new ArrayList<EntityType>();
        }
        return this.documentAuthor;
    }

    /**
     * Gets the value of the documentCategoryAbstract property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentCategoryAbstract property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentCategoryAbstract().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getDocumentCategoryAbstract() {
        if (documentCategoryAbstract == null) {
            documentCategoryAbstract = new ArrayList<Object>();
        }
        return this.documentCategoryAbstract;
    }

    /**
     * Gets the value of the documentCategoryDescriptionText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentCategoryDescriptionText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentCategoryDescriptionText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextType }
     * 
     * 
     */
    public List<TextType> getDocumentCategoryDescriptionText() {
        if (documentCategoryDescriptionText == null) {
            documentCategoryDescriptionText = new ArrayList<TextType>();
        }
        return this.documentCategoryDescriptionText;
    }

    /**
     * Gets the value of the documentContentAbstract property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentContentAbstract property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentContentAbstract().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getDocumentContentAbstract() {
        if (documentContentAbstract == null) {
            documentContentAbstract = new ArrayList<Object>();
        }
        return this.documentContentAbstract;
    }

    /**
     * Gets the value of the documentContentListText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentContentListText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentContentListText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextType }
     * 
     * 
     */
    public List<TextType> getDocumentContentListText() {
        if (documentContentListText == null) {
            documentContentListText = new ArrayList<TextType>();
        }
        return this.documentContentListText;
    }

    /**
     * Gets the value of the documentContributor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentContributor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentContributor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EntityType }
     * 
     * 
     */
    public List<EntityType> getDocumentContributor() {
        if (documentContributor == null) {
            documentContributor = new ArrayList<EntityType>();
        }
        return this.documentContributor;
    }

    /**
     * Gets the value of the documentCopyrightIndicator property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentCopyrightIndicator property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentCopyrightIndicator().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Boolean }
     * 
     * 
     */
    public List<Boolean> getDocumentCopyrightIndicator() {
        if (documentCopyrightIndicator == null) {
            documentCopyrightIndicator = new ArrayList<Boolean>();
        }
        return this.documentCopyrightIndicator;
    }

    /**
     * Gets the value of the documentCountry property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentCountry property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentCountry().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CountryType }
     * 
     * 
     */
    public List<CountryType> getDocumentCountry() {
        if (documentCountry == null) {
            documentCountry = new ArrayList<CountryType>();
        }
        return this.documentCountry;
    }

    /**
     * Gets the value of the documentCoverageAbstract property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentCoverageAbstract property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentCoverageAbstract().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getDocumentCoverageAbstract() {
        if (documentCoverageAbstract == null) {
            documentCoverageAbstract = new ArrayList<Object>();
        }
        return this.documentCoverageAbstract;
    }

    /**
     * Gets the value of the documentCreationDate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentCreationDate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentCreationDate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DateType }
     * 
     * 
     */
    public List<DateType> getDocumentCreationDate() {
        if (documentCreationDate == null) {
            documentCreationDate = new ArrayList<DateType>();
        }
        return this.documentCreationDate;
    }

    /**
     * Gets the value of the documentDescriptionText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentDescriptionText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentDescriptionText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextType }
     * 
     * 
     */
    public List<TextType> getDocumentDescriptionText() {
        if (documentDescriptionText == null) {
            documentDescriptionText = new ArrayList<TextType>();
        }
        return this.documentDescriptionText;
    }

    /**
     * Gets the value of the documentDispositionAuthorityName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentDispositionAuthorityName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentDispositionAuthorityName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextType }
     * 
     * 
     */
    public List<TextType> getDocumentDispositionAuthorityName() {
        if (documentDispositionAuthorityName == null) {
            documentDispositionAuthorityName = new ArrayList<TextType>();
        }
        return this.documentDispositionAuthorityName;
    }

    /**
     * Gets the value of the documentDispositionInstructionText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentDispositionInstructionText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentDispositionInstructionText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextType }
     * 
     * 
     */
    public List<TextType> getDocumentDispositionInstructionText() {
        if (documentDispositionInstructionText == null) {
            documentDispositionInstructionText = new ArrayList<TextType>();
        }
        return this.documentDispositionInstructionText;
    }

    /**
     * Gets the value of the documentDisputedIndicator property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentDisputedIndicator property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentDisputedIndicator().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Boolean }
     * 
     * 
     */
    public List<Boolean> getDocumentDisputedIndicator() {
        if (documentDisputedIndicator == null) {
            documentDisputedIndicator = new ArrayList<Boolean>();
        }
        return this.documentDisputedIndicator;
    }

    /**
     * Gets the value of the documentDisputedReasonAbstract property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentDisputedReasonAbstract property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentDisputedReasonAbstract().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getDocumentDisputedReasonAbstract() {
        if (documentDisputedReasonAbstract == null) {
            documentDisputedReasonAbstract = new ArrayList<Object>();
        }
        return this.documentDisputedReasonAbstract;
    }

    /**
     * Gets the value of the documentEffectiveDate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentEffectiveDate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentEffectiveDate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DateType }
     * 
     * 
     */
    public List<DateType> getDocumentEffectiveDate() {
        if (documentEffectiveDate == null) {
            documentEffectiveDate = new ArrayList<DateType>();
        }
        return this.documentEffectiveDate;
    }

    /**
     * Gets the value of the documentEntrySubmitter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentEntrySubmitter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentEntrySubmitter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PersonType }
     * 
     * 
     */
    public List<PersonType> getDocumentEntrySubmitter() {
        if (documentEntrySubmitter == null) {
            documentEntrySubmitter = new ArrayList<PersonType>();
        }
        return this.documentEntrySubmitter;
    }

    /**
     * Gets the value of the documentEUDataPrivacyIndicator property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentEUDataPrivacyIndicator property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentEUDataPrivacyIndicator().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Boolean }
     * 
     * 
     */
    public List<Boolean> getDocumentEUDataPrivacyIndicator() {
        if (documentEUDataPrivacyIndicator == null) {
            documentEUDataPrivacyIndicator = new ArrayList<Boolean>();
        }
        return this.documentEUDataPrivacyIndicator;
    }

    /**
     * Gets the value of the documentExpirationDate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentExpirationDate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentExpirationDate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DateType }
     * 
     * 
     */
    public List<DateType> getDocumentExpirationDate() {
        if (documentExpirationDate == null) {
            documentExpirationDate = new ArrayList<DateType>();
        }
        return this.documentExpirationDate;
    }

    /**
     * Gets the value of the documentFileControlID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentFileControlID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentFileControlID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getDocumentFileControlID() {
        if (documentFileControlID == null) {
            documentFileControlID = new ArrayList<String>();
        }
        return this.documentFileControlID;
    }

    /**
     * Gets the value of the documentFiledDate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentFiledDate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentFiledDate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DateType }
     * 
     * 
     */
    public List<DateType> getDocumentFiledDate() {
        if (documentFiledDate == null) {
            documentFiledDate = new ArrayList<DateType>();
        }
        return this.documentFiledDate;
    }

    /**
     * Gets the value of the documentFileExtensionText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentFileExtensionText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentFileExtensionText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextType }
     * 
     * 
     */
    public List<TextType> getDocumentFileExtensionText() {
        if (documentFileExtensionText == null) {
            documentFileExtensionText = new ArrayList<TextType>();
        }
        return this.documentFileExtensionText;
    }

    /**
     * Gets the value of the documentFileName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentFileName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentFileName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextType }
     * 
     * 
     */
    public List<TextType> getDocumentFileName() {
        if (documentFileName == null) {
            documentFileName = new ArrayList<TextType>();
        }
        return this.documentFileName;
    }

    /**
     * Gets the value of the documentFormatCategoryAbstract property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentFormatCategoryAbstract property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentFormatCategoryAbstract().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getDocumentFormatCategoryAbstract() {
        if (documentFormatCategoryAbstract == null) {
            documentFormatCategoryAbstract = new ArrayList<Object>();
        }
        return this.documentFormatCategoryAbstract;
    }

    /**
     * Gets the value of the documentFormatAbstract property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentFormatAbstract property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentFormatAbstract().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getDocumentFormatAbstract() {
        if (documentFormatAbstract == null) {
            documentFormatAbstract = new ArrayList<Object>();
        }
        return this.documentFormatAbstract;
    }

    /**
     * Gets the value of the documentGroupID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentGroupID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentGroupID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getDocumentGroupID() {
        if (documentGroupID == null) {
            documentGroupID = new ArrayList<String>();
        }
        return this.documentGroupID;
    }

    /**
     * Gets the value of the documentIdentification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentIdentification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentIdentification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IdentificationType }
     * 
     * 
     */
    public List<IdentificationType> getDocumentIdentification() {
        if (documentIdentification == null) {
            documentIdentification = new ArrayList<IdentificationType>();
        }
        return this.documentIdentification;
    }

    /**
     * Gets the value of the documentInformationCutOffDate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentInformationCutOffDate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentInformationCutOffDate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DateType }
     * 
     * 
     */
    public List<DateType> getDocumentInformationCutOffDate() {
        if (documentInformationCutOffDate == null) {
            documentInformationCutOffDate = new ArrayList<DateType>();
        }
        return this.documentInformationCutOffDate;
    }

    /**
     * Gets the value of the documentIntelligenceCategoryAbstract property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentIntelligenceCategoryAbstract property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentIntelligenceCategoryAbstract().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getDocumentIntelligenceCategoryAbstract() {
        if (documentIntelligenceCategoryAbstract == null) {
            documentIntelligenceCategoryAbstract = new ArrayList<Object>();
        }
        return this.documentIntelligenceCategoryAbstract;
    }

    /**
     * Gets the value of the documentIssuanceLocation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentIssuanceLocation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentIssuanceLocation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LocationType }
     * 
     * 
     */
    public List<LocationType> getDocumentIssuanceLocation() {
        if (documentIssuanceLocation == null) {
            documentIssuanceLocation = new ArrayList<LocationType>();
        }
        return this.documentIssuanceLocation;
    }

    /**
     * Gets the value of the documentIssueDate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentIssueDate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentIssueDate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DateType }
     * 
     * 
     */
    public List<DateType> getDocumentIssueDate() {
        if (documentIssueDate == null) {
            documentIssueDate = new ArrayList<DateType>();
        }
        return this.documentIssueDate;
    }

    /**
     * Gets the value of the documentKeywordAbstract property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentKeywordAbstract property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentKeywordAbstract().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getDocumentKeywordAbstract() {
        if (documentKeywordAbstract == null) {
            documentKeywordAbstract = new ArrayList<Object>();
        }
        return this.documentKeywordAbstract;
    }

    /**
     * Gets the value of the documentLanguage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentLanguage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentLanguage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LanguageType }
     * 
     * 
     */
    public List<LanguageType> getDocumentLanguage() {
        if (documentLanguage == null) {
            documentLanguage = new ArrayList<LanguageType>();
        }
        return this.documentLanguage;
    }

    /**
     * Gets the value of the documentLastModifiedDate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentLastModifiedDate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentLastModifiedDate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DateType }
     * 
     * 
     */
    public List<DateType> getDocumentLastModifiedDate() {
        if (documentLastModifiedDate == null) {
            documentLastModifiedDate = new ArrayList<DateType>();
        }
        return this.documentLastModifiedDate;
    }

    /**
     * Gets the value of the documentLocation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentLocation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentLocation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LocationType }
     * 
     * 
     */
    public List<LocationType> getDocumentLocation() {
        if (documentLocation == null) {
            documentLocation = new ArrayList<LocationType>();
        }
        return this.documentLocation;
    }

    /**
     * Gets the value of the documentLocationURI property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentLocationURI property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentLocationURI().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AnyURI }
     * 
     * 
     */
    public List<AnyURI> getDocumentLocationURI() {
        if (documentLocationURI == null) {
            documentLocationURI = new ArrayList<AnyURI>();
        }
        return this.documentLocationURI;
    }

    /**
     * Gets the value of the documentManagementCyclePeriodText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentManagementCyclePeriodText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentManagementCyclePeriodText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextType }
     * 
     * 
     */
    public List<TextType> getDocumentManagementCyclePeriodText() {
        if (documentManagementCyclePeriodText == null) {
            documentManagementCyclePeriodText = new ArrayList<TextType>();
        }
        return this.documentManagementCyclePeriodText;
    }

    /**
     * Gets the value of the documentOtherRecipient property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentOtherRecipient property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentOtherRecipient().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EntityType }
     * 
     * 
     */
    public List<EntityType> getDocumentOtherRecipient() {
        if (documentOtherRecipient == null) {
            documentOtherRecipient = new ArrayList<EntityType>();
        }
        return this.documentOtherRecipient;
    }

    /**
     * Gets the value of the documentPermanentRecordIndicator property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentPermanentRecordIndicator property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentPermanentRecordIndicator().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Boolean }
     * 
     * 
     */
    public List<Boolean> getDocumentPermanentRecordIndicator() {
        if (documentPermanentRecordIndicator == null) {
            documentPermanentRecordIndicator = new ArrayList<Boolean>();
        }
        return this.documentPermanentRecordIndicator;
    }

    /**
     * Gets the value of the documentPhysicalMediumCategoryAbstract property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentPhysicalMediumCategoryAbstract property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentPhysicalMediumCategoryAbstract().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getDocumentPhysicalMediumCategoryAbstract() {
        if (documentPhysicalMediumCategoryAbstract == null) {
            documentPhysicalMediumCategoryAbstract = new ArrayList<Object>();
        }
        return this.documentPhysicalMediumCategoryAbstract;
    }

    /**
     * Gets the value of the documentPhysicalMediumText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentPhysicalMediumText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentPhysicalMediumText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextType }
     * 
     * 
     */
    public List<TextType> getDocumentPhysicalMediumText() {
        if (documentPhysicalMediumText == null) {
            documentPhysicalMediumText = new ArrayList<TextType>();
        }
        return this.documentPhysicalMediumText;
    }

    /**
     * Gets the value of the documentPostDate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentPostDate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentPostDate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DateType }
     * 
     * 
     */
    public List<DateType> getDocumentPostDate() {
        if (documentPostDate == null) {
            documentPostDate = new ArrayList<DateType>();
        }
        return this.documentPostDate;
    }

    /**
     * Gets the value of the documentPrivacyActIndicator property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentPrivacyActIndicator property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentPrivacyActIndicator().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Boolean }
     * 
     * 
     */
    public List<Boolean> getDocumentPrivacyActIndicator() {
        if (documentPrivacyActIndicator == null) {
            documentPrivacyActIndicator = new ArrayList<Boolean>();
        }
        return this.documentPrivacyActIndicator;
    }

    /**
     * Gets the value of the documentPublicationDate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentPublicationDate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentPublicationDate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DateType }
     * 
     * 
     */
    public List<DateType> getDocumentPublicationDate() {
        if (documentPublicationDate == null) {
            documentPublicationDate = new ArrayList<DateType>();
        }
        return this.documentPublicationDate;
    }

    /**
     * Gets the value of the documentReceivedDate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentReceivedDate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentReceivedDate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DateType }
     * 
     * 
     */
    public List<DateType> getDocumentReceivedDate() {
        if (documentReceivedDate == null) {
            documentReceivedDate = new ArrayList<DateType>();
        }
        return this.documentReceivedDate;
    }

    /**
     * Gets the value of the documentRecipient property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentRecipient property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentRecipient().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EntityType }
     * 
     * 
     */
    public List<EntityType> getDocumentRecipient() {
        if (documentRecipient == null) {
            documentRecipient = new ArrayList<EntityType>();
        }
        return this.documentRecipient;
    }

    /**
     * Gets the value of the documentRelatedResourceText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentRelatedResourceText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentRelatedResourceText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextType }
     * 
     * 
     */
    public List<TextType> getDocumentRelatedResourceText() {
        if (documentRelatedResourceText == null) {
            documentRelatedResourceText = new ArrayList<TextType>();
        }
        return this.documentRelatedResourceText;
    }

    /**
     * Gets the value of the documentRightsText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentRightsText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentRightsText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextType }
     * 
     * 
     */
    public List<TextType> getDocumentRightsText() {
        if (documentRightsText == null) {
            documentRightsText = new ArrayList<TextType>();
        }
        return this.documentRightsText;
    }

    /**
     * Gets the value of the documentSensitivityAbstract property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentSensitivityAbstract property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentSensitivityAbstract().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getDocumentSensitivityAbstract() {
        if (documentSensitivityAbstract == null) {
            documentSensitivityAbstract = new ArrayList<Object>();
        }
        return this.documentSensitivityAbstract;
    }

    /**
     * Gets the value of the documentSequenceID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentSequenceID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentSequenceID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getDocumentSequenceID() {
        if (documentSequenceID == null) {
            documentSequenceID = new ArrayList<String>();
        }
        return this.documentSequenceID;
    }

    /**
     * Gets the value of the documentSoftware property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentSoftware property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentSoftware().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SoftwareType }
     * 
     * 
     */
    public List<SoftwareType> getDocumentSoftware() {
        if (documentSoftware == null) {
            documentSoftware = new ArrayList<SoftwareType>();
        }
        return this.documentSoftware;
    }

    /**
     * Gets the value of the documentSource property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentSource property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentSource().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EntityType }
     * 
     * 
     */
    public List<EntityType> getDocumentSource() {
        if (documentSource == null) {
            documentSource = new ArrayList<EntityType>();
        }
        return this.documentSource;
    }

    /**
     * Gets the value of the documentSourceText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentSourceText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentSourceText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextType }
     * 
     * 
     */
    public List<TextType> getDocumentSourceText() {
        if (documentSourceText == null) {
            documentSourceText = new ArrayList<TextType>();
        }
        return this.documentSourceText;
    }

    /**
     * Gets the value of the documentStatus property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentStatus property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentStatus().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StatusType }
     * 
     * 
     */
    public List<StatusType> getDocumentStatus() {
        if (documentStatus == null) {
            documentStatus = new ArrayList<StatusType>();
        }
        return this.documentStatus;
    }

    /**
     * Gets the value of the documentStatusCategoryAbstract property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentStatusCategoryAbstract property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentStatusCategoryAbstract().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getDocumentStatusCategoryAbstract() {
        if (documentStatusCategoryAbstract == null) {
            documentStatusCategoryAbstract = new ArrayList<Object>();
        }
        return this.documentStatusCategoryAbstract;
    }

    /**
     * Gets the value of the documentSubjectAbstract property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentSubjectAbstract property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentSubjectAbstract().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getDocumentSubjectAbstract() {
        if (documentSubjectAbstract == null) {
            documentSubjectAbstract = new ArrayList<Object>();
        }
        return this.documentSubjectAbstract;
    }

    /**
     * Gets the value of the documentSubmissionAmount property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentSubmissionAmount property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentSubmissionAmount().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AmountType }
     * 
     * 
     */
    public List<AmountType> getDocumentSubmissionAmount() {
        if (documentSubmissionAmount == null) {
            documentSubmissionAmount = new ArrayList<AmountType>();
        }
        return this.documentSubmissionAmount;
    }

    /**
     * Gets the value of the documentSubmitter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentSubmitter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentSubmitter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EntityType }
     * 
     * 
     */
    public List<EntityType> getDocumentSubmitter() {
        if (documentSubmitter == null) {
            documentSubmitter = new ArrayList<EntityType>();
        }
        return this.documentSubmitter;
    }

    /**
     * Gets the value of the documentSummaryText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentSummaryText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentSummaryText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextType }
     * 
     * 
     */
    public List<TextType> getDocumentSummaryText() {
        if (documentSummaryText == null) {
            documentSummaryText = new ArrayList<TextType>();
        }
        return this.documentSummaryText;
    }

    /**
     * Gets the value of the documentSupplementalMarkingText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentSupplementalMarkingText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentSupplementalMarkingText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextType }
     * 
     * 
     */
    public List<TextType> getDocumentSupplementalMarkingText() {
        if (documentSupplementalMarkingText == null) {
            documentSupplementalMarkingText = new ArrayList<TextType>();
        }
        return this.documentSupplementalMarkingText;
    }

    /**
     * Gets the value of the documentTitleAlternativeText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentTitleAlternativeText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentTitleAlternativeText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextType }
     * 
     * 
     */
    public List<TextType> getDocumentTitleAlternativeText() {
        if (documentTitleAlternativeText == null) {
            documentTitleAlternativeText = new ArrayList<TextType>();
        }
        return this.documentTitleAlternativeText;
    }

    /**
     * Gets the value of the documentTitleText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentTitleText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentTitleText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextType }
     * 
     * 
     */
    public List<TextType> getDocumentTitleText() {
        if (documentTitleText == null) {
            documentTitleText = new ArrayList<TextType>();
        }
        return this.documentTitleText;
    }

    /**
     * Gets the value of the documentVitalIndicator property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentVitalIndicator property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentVitalIndicator().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Boolean }
     * 
     * 
     */
    public List<Boolean> getDocumentVitalIndicator() {
        if (documentVitalIndicator == null) {
            documentVitalIndicator = new ArrayList<Boolean>();
        }
        return this.documentVitalIndicator;
    }

    /**
     * Gets the value of the documentAugmentationPoint property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentAugmentationPoint property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentAugmentationPoint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getDocumentAugmentationPoint() {
        if (documentAugmentationPoint == null) {
            documentAugmentationPoint = new ArrayList<Object>();
        }
        return this.documentAugmentationPoint;
    }

}
