//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.27 at 03:48:01 PM EST 
//


package gov.niem.core;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import gov.niem.adapters.xs.NonNegativeInteger;


/**
 * A data type for a picture or visual representation of something.
 * 
 * <p>Java class for ImageType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ImageType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://release.niem.gov/niem/niem-core/5.0/}BinaryType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}ImageHeightValue" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}ImageLocation" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}ImageWidthValue" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://release.niem.gov/niem/niem-core/5.0/}ImageAugmentationPoint" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;anyAttribute processContents='lax' namespace='urn:us:gov:ic:ntk urn:us:gov:ic:ism'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ImageType", namespace = "http://release.niem.gov/niem/niem-core/5.0/", propOrder = {
    "imageHeightValue",
    "imageLocation",
    "imageWidthValue",
    "imageAugmentationPoint"
})
public class ImageType
    extends BinaryType
{

    @XmlElement(name = "ImageHeightValue", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<NonNegativeInteger> imageHeightValue;
    @XmlElement(name = "ImageLocation", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<LocationType> imageLocation;
    @XmlElement(name = "ImageWidthValue", namespace = "http://release.niem.gov/niem/niem-core/5.0/", nillable = true)
    protected List<NonNegativeInteger> imageWidthValue;
    @XmlElement(name = "ImageAugmentationPoint", namespace = "http://release.niem.gov/niem/niem-core/5.0/")
    protected List<Object> imageAugmentationPoint;

    /**
     * Gets the value of the imageHeightValue property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the imageHeightValue property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getImageHeightValue().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NonNegativeInteger }
     * 
     * 
     */
    public List<NonNegativeInteger> getImageHeightValue() {
        if (imageHeightValue == null) {
            imageHeightValue = new ArrayList<NonNegativeInteger>();
        }
        return this.imageHeightValue;
    }

    /**
     * Gets the value of the imageLocation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the imageLocation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getImageLocation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LocationType }
     * 
     * 
     */
    public List<LocationType> getImageLocation() {
        if (imageLocation == null) {
            imageLocation = new ArrayList<LocationType>();
        }
        return this.imageLocation;
    }

    /**
     * Gets the value of the imageWidthValue property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the imageWidthValue property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getImageWidthValue().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NonNegativeInteger }
     * 
     * 
     */
    public List<NonNegativeInteger> getImageWidthValue() {
        if (imageWidthValue == null) {
            imageWidthValue = new ArrayList<NonNegativeInteger>();
        }
        return this.imageWidthValue;
    }

    /**
     * Gets the value of the imageAugmentationPoint property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the imageAugmentationPoint property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getImageAugmentationPoint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getImageAugmentationPoint() {
        if (imageAugmentationPoint == null) {
            imageAugmentationPoint = new ArrayList<Object>();
        }
        return this.imageAugmentationPoint;
    }

}
