//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.27 at 04:09:22 PM EST 
//


package gov.niem.core;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MessageCategoryFATCACodeSimpleType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MessageCategoryFATCACodeSimpleType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="FATCA"/&gt;
 *     &lt;enumeration value="Other"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "MessageCategoryFATCACodeSimpleType", namespace = "http://release.niem.gov/niem/niem-core/5.0/")
@XmlEnum
public enum MessageCategoryFATCACodeSimpleType {


    /**
     * Foreign Account Tax Compliance Act
     * 
     */
    FATCA("FATCA"),

    /**
     * Other
     * 
     */
    @XmlEnumValue("Other")
    OTHER("Other");
    private final String value;

    MessageCategoryFATCACodeSimpleType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MessageCategoryFATCACodeSimpleType fromValue(String v) {
        for (MessageCategoryFATCACodeSimpleType c: MessageCategoryFATCACodeSimpleType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
